### PR TITLE
[DO NOT MERGE] Update Data summary provider with new ABI layout

### PR DESCRIPTION
**Pull request by itaiferber**
Updates the summary provider for `Data` in conjunction with layout changes in apple/swift#20225
The test here will fail without that PR.

### CODE REVIEW

**Comment by itaiferber** [comment]
Please test with following pull request:
apple/swift#20225

@swift-ci Please test

**Comment by itaiferber** [comment]
(Now that tests have passed on this and apple/swift#20225, I plan on merging them in parallel once we have approval.)

**Review by dcci — APPROVED** [review]
LGTM, thanks for all the comments in the formatter. They make the code much more readable.
The only thing I can ask you is whether you can clang-format the patch (if you didn't already) before committing to keep the style consistent with what's there already.

**Comment by itaiferber** [comment]
@dcci Sure, I'll run that now

**Comment by dcci** [comment]
Other than that, feel free to merge.

**Comment by itaiferber** [comment]
Please test with following pull request:
apple/swift#20225

@swift-ci Please test

**Review by jimingham — CHANGES_REQUESTED** [review]
LGTM.

**Comment by jimingham** [comment]
Ack chose the wrong menu item.  Don't need changes...

**Review by jimingham — APPROVED** [review]

**Comment by itaiferber** [comment]
@jimingham @dcci Thanks for the review!

**Pull request merged**
