### PR TITLE
[ExpressionParser] Fix typo in SwiftPersistentExpressionState

### PR DESCRIPTION
**Pull request by bulbazord**
cc @dcci @JDevlieghere @compnerd

### CODE REVIEW

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by bulbazord** [comment]
ping @compnerd

**Comment by JDevlieghere** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by bulbazord** [comment]
Ok, forgot to fix one instance of eKindClang. Should work now.

**Comment by bulbazord** [comment]
@swift-ci please tests and merge

**Comment by compnerd** [comment]
@swift-ci please test

**Pull request merged**
