### PR TITLE
[InstrumentationRuntime] Remove duplicated plugin implementation.

### PR DESCRIPTION
**Pull request by dcci**
One is enough.

### CODE REVIEW

**Comment by dcci** [comment]
I'm going ahead and try to test and merge this, but your review is of course appreciated.

**Comment by dcci** [comment]
@swift-ci test and merge

**Comment by vedantk** [comment]
If the idea is to move this upstream, this is fine, but I don’t think the plugin itself is duplicated.

**Comment by dcci** [comment]
I'm confused by your reply. The plugin is already upstream, it just has a different name.
`UBSan` VS `UndefinedBehaviour`. Downstream had both, and one was unused.

**Comment by vedantk** [comment]
Yikes. Now this makes sense. Thank you.

**Comment by dcci** [comment]
No worries :) Thank you!

**Pull request merged**
