### PR TITLE
Updated inout location to Swift 3 model

### PR DESCRIPTION
**Pull request by manavgabhawala**
Updates the test cases to change the `inout` location to the new Swift 3 model

### CODE REVIEW

**Comment by benlangmuir** [comment]
I think Enrico may have fixed this in 212577292fd1993fd50cd2bcb1cc83c9d06860a2 already.  Assigning to him.

**Comment by egranata** [comment]
@manavgabhawala it looks like your fix is more thorough that mine. Can I get you to rebase your diff against master (essentially, a lot of the changes just go away)? I'll gladly approve after that.

**Comment by manavgabhawala** [comment]
@egranata done

**Comment by egranata** [comment]
@manavgabhawala Thanks!

**Pull request merged**
