### PR TITLE
[CMake] Link against host swiftReflection instead of target swiftRefl…

### PR DESCRIPTION
**Pull request by bulbazord**
…ection

I'm doing this because I think we should be linking against the swiftReflection library built for the host. The other swift libraries being linked against are all host libraries, so I don't think swiftReflection is a special case.

### CODE REVIEW

**Comment by bulbazord** [comment]
cc @compnerd @dcci @weliveindetail

**Review by weliveindetail — CHANGES_REQUESTED** [review]
While I'm not familiar with the reasoning behind this code, looking at the history shows that https://github.com/apple/swift-lldb/commit/cb495cf645d3b22083c7b5df4e8797adc15e2354 did this exact same change some months ago and https://github.com/apple/swift-lldb/commit/209bc1fb8ecaeb34c13a4047f2f78a79e9dcde20 reverted it.

Thus, swiftReflection seems to be some kind of special case and we should understand the details before landing this.

**Comment by fredriss** [comment]
Hmmm, I don't remember reverting this, thus I don't remember the reasons and my commit message was rather terse. I suppose it broke something in LLDB. We did change the Reflection build in the meantime to unconditionally build a static host library. The change looks reasonable to me.

**Review by weliveindetail — APPROVED** [review]
Ok, let's give it a try then.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by bulbazord** [comment]
It seems like the reverts were to match whatever was on Swift-5.0's branch, which probably meant that we were not building Reflection for the Host there. I don't think that's the case anymore though, so I think this should be okay.

**Pull request merged**
