### PR TITLE
Adapt lldb to the new swift weak reference representation.

### PR DESCRIPTION
**Pull request by gparker42**
<rdar://problem/29765836>

### CODE REVIEW

**Comment by jimingham** [comment]
@swift-ci please test

**Comment by gparker42** [comment]
https://github.com/apple/swift/pull/5282

@swift-ci please test

**Comment by jimingham** [comment]
Oh, right, your test is actually likely to build...

**Comment by gparker42** [comment]
apple/swift#5282

@swift-ci please test

**Pull request merged**
