### PR TITLE
[SwiftASTContext] Remove dead code. NFCI.

### PR DESCRIPTION
**Pull request by dcci**

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci please test and merge

**Comment by jimingham** [comment]
All the FindXType(s)OrDecl(s) functions have a FindType equivalent.  It seems a little odd to remove the "Type" version from just one of them.

**Comment by dcci** [comment]
As I discover more dead code, I'm going to remove it.

**Comment by dcci** [comment]
But as a general practice, I don't think we should leave dead code in tree just for the sake of internal API symmetry.

**Pull request merged**
