### PR TITLE
Normalize the LLVM cmake path before appending it to the module path

### PR DESCRIPTION
**Pull request by hughbe**
`LLVM_CMAKE_PATH` has backlashes in it. CMake then tries to append this to `CMAKE_MODULE_PATH` but gets confused and errors out as it thinks we're providing an escape sequence (that's unknown, causing generation to fail)

E.g "C:\Users\hugh\..."

### CODE REVIEW

**Comment by hughbe** [comment]
@swift-ci please test

**Comment by hughbe** [comment]
@jimingham PTAL, should this go to upstream LLDB?

**Comment by hughbe** [comment]
and @llvm-beanz 'cause you're the CMake guy, at least looking at commits

**Comment by llvm-beanz** [comment]
This change looks fine, but should definitely go to LLVM.org. The CMake logic being changed here is identical upstream.

**Comment by jimingham** [comment]
By default, all commits that are in non-swift code should go into llvm.org and get merged back to the swift lldb.  That way they everybody gets the benefit of the changes, and they won't cause later merge conflicts if they get fixed differently upstream.

**Comment by hughbe** [comment]
@swift-ci please test

**Comment by hughbe** [comment]
I've updated the PR to cherry-pick my commit from upstream lldb

**Comment by llvm-beanz** [comment]
LGTM!

**Pull request merged**
