### PR TITLE
Simplify Swift dylib rules in Makefile.rules and add -dylib back to t…

### PR DESCRIPTION
**Pull request by adrian-prantl**
…he flags.

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Review by nathawes — APPROVED** [review]
Oops, didn't realize I'd dropped -dylib sorry! LGTM.

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Pull request merged**
