### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by bulbazord**
This is a merge from llvm/master into upstream-with-swift with any needed adjustments to account for swift.

### CODE REVIEW

**Comment by bulbazord** [comment]
@swift-ci please test

**Comment by bulbazord** [comment]
@swift-ci please test

**Comment by vedantk** [comment]
@xiaobai thanks for working on this! It looks like swift-corelibs-libdispatch is failing to build on Linux (cc @ktopley-apple @compnerd), and that TestResilience may need to be xfailed on Darwin in this PR.

**Comment by vedantk** [comment]
Happy to merge a rebased version of this in if it fixes the build, we can get to the tests later.

**Comment by bulbazord** [comment]
@vedantk: I worked with @compnerd the other day to resolve some of the swift-corelibs-libdispatch issues. I plan on rebasing this later today which is why I haven't kicked off another test.

**Comment by bulbazord** [comment]
I rebased this but I expect this to fail because swift-clang's merge is too old (looks to be ~12 hours behind). However we hopefully will be able to uncover any other issues.

**Comment by bulbazord** [comment]
@swift-ci please test

**Comment by bulbazord** [comment]
Looks like I might have messed up part of the merge because of some SWIG change. I'll take a look.

**Comment by bulbazord** [comment]
@swift-ci please test

**Comment by bulbazord** [comment]
Looks like clang got a merge and now lldb actually builds! I think it fails when testing though.

@JDevlieghere @vedantk y'all okay with this going in? :)

**Comment by vedantk** [comment]
Yes, thank you! Happy to push the 'merge' button for you if that's needed. Well, actually, right _now_ I can't because github says there's another conflict. Let me look at what it is.

**Comment by bulbazord** [comment]
@vedantk I'm able to merge it. Just wanted to make sure you were good with it.

**Comment by bulbazord** [comment]
@vedantk Thanks for the support! :)

**Pull request merged**
