### PR TITLE
Revert "Implement ComputeSwiftResourceDirectory work on all platforms"

### PR DESCRIPTION
**Pull request by weliveindetail**
This reverts commit c7d5112a49d01cdbf740e52330b07d161f90e4dc to see if it fixes PR testing issues on Linux.

### CODE REVIEW

**Comment by weliveindetail** [comment]
@swift-ci please test

**Review by dcci — COMMENTED** [review]
[cc:ing the folks at Facebook who authored the change]
Can you please elaborate on what you think the issue is and why this revert would fix? 
This would be the minimum amount needed to justify the revert, and it's also useful for commit archeology.

**Comment by dcci** [comment]
+ Slava who hit this issue on the bots a certain number of times.

**Comment by weliveindetail** [comment]
@dcci Can we run this through swift-PR-Linux somehow?

**Comment by weliveindetail** [comment]
And: as the initial comment states, this is mainly a test whether this change introduced the issue.

**Comment by weliveindetail** [comment]
> Can you please elaborate on what you think the issue is and why this revert would fix?

In incremental builds LLDB's copy of the Swift resource directory doesn't get updated. This is either a feature or a bug of `add_custom_command_target()`. There were concerns about it in the review that were not acted upon:
`https://github.com/apple/swift-lldb/pull/1436/commits/c7d5112a49d01cdbf740e52330b07d161f90e4dc#diff-301dd16d95cf5bb591982af5b0879431R189`

The same mechanism exists for Clang resources but seems less critical as they change rarely.
Apparently, with this change the original location of the resource directory (or any other one) is not a fallback option anymore. Thus, builds fail in case of stale Swift resources from previous builds in PR testing now.

Possible fixes:
* run before each incremental build: `$ rm -rf build/buildbot_linux/ldb-linux-x86_64/lib/lldb`
* merge this PR
* copy the resources directories unconditionally

**Comment by adrian-prantl** [comment]
@dcci see <rdar://problem/53766821>

**Comment by dcci** [comment]
@compnerd @xiaobai @gmittert can we go ahead and merge this?

**Comment by bulbazord** [comment]
If the CMake is the only issue, could we just revert the CMake portion? This provides windows functionality that we need. We can clean up the portion of code that looks in `lib/lldb/swift` since that won't be used anymore, but the implementation works so that if it's not there it will look elsewhere instead of failing immediately.

**Comment by weliveindetail** [comment]
@xiaobai Sure, feel free to find a more appropriate fix. I think you made the right observation in the review already. Otherwise, let's merge this PR.

**Review by bulbazord — CHANGES_REQUESTED** [review]
#1846

**Comment by dcci** [comment]
Superseded by #1846

**Pull request closed without merging**
