### PR TITLE
Fix lldb test for +0.

### PR DESCRIPTION
**Pull request by gottesmm**
rdar://34222540

### CODE REVIEW

**Comment by gottesmm** [comment]
apple/swift#14953

@swift-ci test

**Comment by gottesmm** [comment]
Just waiting for this #15361 to land.

**Comment by gottesmm** [comment]
Erm... apple/swift#15361

**Comment by vedantk** [comment]
@swift-ci test Linux platform

**Comment by vedantk** [comment]
@gottesmm I haven't had a chance to test apple/swift#15361 on a Linux machine. If this doesn't go through, ping me and I can force-merge this.

**Comment by gottesmm** [comment]
@vedantk This is a cross repo PR. So I need to restart.

**Comment by gottesmm** [comment]
apple/swift#14953

@swift-ci test linux platform

**Comment by gottesmm** [comment]
apple/swift#14953

@swift-ci test linux platform

**Comment by vedantk** [comment]
apple/swift#14953

@swift-ci test linux platform

**Pull request merged**
