### PR TITLE
[MemoryReader] Only dump a reasonable number of bytes.

### PR DESCRIPTION
**Pull request by dcci**
Otherwise the log gets too verbose, not really readable.
Discussed with (and proposed by) Adrian.

<rdar://problem/45592295>

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci test and merge

**Comment by jimingham** [comment]
Can you change this so you check whether the log is Verbose, and emit the full memory if it is verbose?

**Comment by jimingham** [comment]
You can just call GetVerbose on the Log object you get back.

**Comment by adrian-prantl** [comment]
Could we hide the entire MemoryReader logging behind the verbose flag? Or am I biased just because *I* don't know how to make sense of the dumped bytes?  :-)

**Comment by dcci** [comment]
I think it's useful to get errors from the memory reader because it means you're reading something you shouldn't have, so I'm less happy about making the whole thing guarded by verbose. What Jim suggests is fine, I think.

**Comment by dcci** [comment]
@jimingham updated the review, please take a look.

**Comment by dcci** [comment]
@swift-ci please test and merge

**Review by jimingham — APPROVED** [review]
That's fine.

**Pull request merged**
