### PR TITLE
[test] Disable TestRepl{Dictionary,NSString} in PR testing

### PR DESCRIPTION
**Pull request by vedantk**
They appear to be flaky.

rdar://37407231

### CODE REVIEW

**Comment by vedantk** [comment]
@swift-ci test

**Comment by jimingham** [comment]
pexpect seems to be flakey and beyond our control.  All the REPL tests that were written using lldbsuite.test.lldbrepl should be converted to use lldbsuite.test.lldbinrepl.  That uses the expression parser directly, and is much more stable.  Those tests are actually much easier to read as well.

I'm fine with not using these tests for swiftpr, but we should remember to get back to them and convert them to the lldbinrepl form instead.

**Comment by vedantk** [comment]
Gotcha, I've got a radar to do just that.

**Comment by jimingham** [comment]
Excellent!

**Comment by dcci** [comment]
After a fair amount of yak shaving, #340 and #343 fix this.

**Pull request merged**
