### PR TITLE
Sketch data formatters for new range types, introduced in SE-0065 "A New Model for Collections and Indices"

### PR DESCRIPTION
**Pull request by gribozavr**

### CODE REVIEW

**Comment by gribozavr** [comment]
@egranata @tfiala Could you review, please?

**Comment by tfiala** [comment]
Looks reasonable to me.  This is Enrico's code, so his opinion counts far more.

Let's give it a test run as well.

**Comment by tfiala** [comment]
@swift-ci Please test

**Comment by gribozavr** [comment]
This code depends on https://github.com/apple/swift/pull/2108, so it won't work as-is.

**Comment by tfiala** [comment]
Okay this build looks like it was stuck behind the triple breakage.

**Comment by tfiala** [comment]
> This code depends on apple/swift#2108, so it won't work as-is.

I see, okay.

**Comment by egranata** [comment]
I am not familiar with the details of the new collection model, but the code looks very reasonable - assuming it passes our test suite whenever the main change gets pulled in, this looks good to me.

**Pull request merged**
