### PR TITLE
Revert "Refactor SwiftASTContext::GetResourceDir() to make it testable"

### PR DESCRIPTION
**Pull request by dcci**
This reverts commit 331fafaf164cadfce2d388d2e44c8f529cc9b374.

### CODE REVIEW

**Comment by dcci** [comment]
This commit seems to cause an infinite loop in the lldb testsuite. Reverting to unblock swift.

**Comment by adrian-prantl** [comment]
Is it because m_once_flag is uninitialized?

**Comment by adrian-prantl** [comment]
Do you have any instructions for reproducing?

**Comment by dcci** [comment]
`ninja check-lldb` on a Linux machine. We reproduced on real hw, but I don't see why this shouldn't repro on a docker instance.

**Pull request merged**
