### PR TITLE
[Swift] Remove old pre-RemoteAST code path for getting field offsets

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Review by dcci — APPROVED** [review]
LGTM

**Comment by dcci** [comment]
(I was actually just looking at that code :)

**Comment by dcci** [comment]
@swift-ci please test

**Comment by slavapestov** [comment]
@dcci I'm still confused if I should merge change into `stable`, or `upstream-with-swift`, or `swift-5.0-branch`, etc. This is not a bug fix (unlike https://github.com/apple/swift-lldb/pull/275) so it doesn't need to go into 4.1.

Actually if you guys could handle the cherry-picking and merging of both of these PRs it would be amazing :-)

**Comment by dcci** [comment]
I think the correct workflow is merging to `upstream-with-swift` and then backporting to `stable`.
This way the fix will last forever (if you do backwards, the fix might disappear) cc: @fredriss as he has a lot of experience with merges.

At the moment swift `upstream-with-swift` branch builds but it's not green, I'm currently working to fix all the failures & use that as base for future changes.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by dcci** [comment]
@slavapestov Also, yes, no worries, I'm going to handle the merge/fixes on your behalf. (once I get out of this Quicksand)

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@dcci Thanks :) I changed the base branch to 'stable', but I guess I jumped the gun. Anyway the patch applies cleanly on both.

**Comment by fredriss** [comment]
@slavapestov please never merge to stable unless the change is coupled to one on swift/master. It should go to upstream-with-swift and swift-5.0-branch (or llvm-swift5-transition, it doesn't matter)

**Comment by fredriss** [comment]
(it'll be automerged into master)

**Pull request closed without merging**
