### PR TITLE
Cherry-pick crashlog bugfixes

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@dcci it looks like this somehow regressed since yesterday. I thought these fixes were already on the branch...

**Comment by dcci** [comment]
ehm, I thought these were there too?

**Review by dcci — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@fredriss Could you perhaps force-merge this? This is blocking all CMake LLDB bots.

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Pull request merged**
