### PR TITLE
[SwiftFormatters] Don't print the padding for SIMD3.

### PR DESCRIPTION
**Pull request by dcci**
<rdar://problem/50172723>

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci test and merge

**Review by stephentyrone — APPROVED** [review]

**Comment by dcci** [comment]
wrong branch, let me rectify that.

**Comment by dcci** [comment]
@swift-ci test and merge

**Review by stephentyrone — APPROVED** [review]
Still looks good.

**Comment by dcci** [comment]
@swift-ci test linux

**Pull request merged**
