### PR TITLE
[5.0] Fix PythonString::GetString for >=python-3.7

### PR DESCRIPTION
**Pull request by jrose-apple**
Cherry-pick of https://reviews.llvm.org/rLLDB337908 to swift-5.0-branch.

[SR-9180](https://bugs.swift.org/browse/SR-9180)

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
Uh, hm. We took Linux off the requirements for the Swift repo for swift-5.0-branch because the corelibs repos haven't branched. Should the same have been done for LLDB? Or should I just wait two weeks?

**Comment by fredriss** [comment]
@shahmishal See Jordan's comment. I have a bunch of stuff to integrate, I really need PR testing to work on the 5.0 branch

**Comment by fredriss** [comment]
Note that this is dangerous. LLDB works on the 5.0 branch which is then auto merged into stable. If we don't test on Linux on the 5.0 branch we might break Linux PR testing on stable as a side effect.

**Comment by shahmishal** [comment]
@milseman was working on creating bug report on bugs.swift.org.

We are seeing this issue because we auto merge master into swift-5.0-branch for swift-corelibs-* projects. The change corresponding to foundation needs to be cherrypicked into swift-5.0-branch or reverted.

**Comment by milseman** [comment]
https://bugs.swift.org/browse/SR-9189 was what I filed

**Comment by jrose-apple** [comment]
@swift-ci Please test Linux

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
@fredriss Do I need special approval to merge this? It's mostly just a favor for those using Python 3.

**Comment by fredriss** [comment]
Nope, that's fine. I just merged it

**Pull request merged**
