### PR TITLE
 Support building DWARF-only (no .dSYM) Swift testcases.

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by dcci** [comment]
@adrian-prantl I'm seeing a lot of failures.
Could they be related to your commits?

```
17:36:23 ======================================================================
17:36:23 ERROR: test_dwo (TestREPLImportDispatch.TestREPLImportDispatch)
17:36:23 ----------------------------------------------------------------------
17:36:23 Error when building test subject.
17:36:23 
17:36:23 Build Command:
17:36:23 make VPATH=/home/buildnode/jenkins/workspace/oss-lldb-incremental-linux-ubuntu-16_04/lldb/packages/Python/lldbsuite/test/repl/import-dispatch -C /home/buildnode/jenkins/workspace/oss-lldb-incremental-linux-ubuntu-16_04/Ninja-ReleaseAssert/lldb-linux-x86_64/lldb-test-build.noindex/repl/import-dispatch/TestREPLImportDispatch.test_dwo -I /home/buildnode/jenkins/workspace/oss-lldb-incremental-linux-ubuntu-16_04/lldb/packages/Python/lldbsuite/test/repl/import-dispatch -f /home/buildnode/jenkins/workspace/oss-lldb-incremental-linux-ubuntu-16_04/lldb/packages/Python/lldbsuite/test/repl/import-dispatch/Makefile MAKE_DSYM=NO MAKE_DWO=YES ARCH=x86_64  CC=/home/buildnode/jenkins/workspace/oss-lldb-incremental-linux-ubuntu-16_04/Ninja-ReleaseAssert/llvm-linux-x86_64/bin/clang-7 SWIFTC=/home/buildnode/jenkins/workspace/oss-lldb-incremental-linux-ubuntu-16_04/Ninja-ReleaseAssert/swift-linux-x86_64/bin/swiftc 
17:36:23 
17:36:23 Build Command Output:
17:36:23 ../../make/Makefile.rules:612: warning: overriding recipe for target 'a.out'
17:36:23 /home/buildnode/jenkins/workspace/oss-lldb-incremental-linux-ubuntu-16_04/lldb/packages/Python/lldbsuite/test/repl/import-dispatch/Makefile:6: warning: ignoring old recipe for target 'a.out'
17:36:23 make: ../../make/find-swift.py: Command not found
17:36:23 <unknown>:0: error: unknown argument: '-Xlinker'
17:36:23 <unknown>:0: error: unknown argument: '-rpath'
17:36:23 <unknown>:0: error: unknown argument: '-Xlinker'
17:36:23 <unknown>:0: error: unknown argument: '-Xlinker'
17:36:23 <unknown>:0: error: unknown argument: '-rpath'
17:36:23 <unknown>:0: error: unknown argument: '-Xlinker'
17:36:23 make: *** [input.o] Error 1
```

**Pull request merged**
