### PR TITLE
Revert "Temporarily disable SwiftFoundationTest on linux."

### PR DESCRIPTION
**Pull request by compnerd**
This reverts commit 9086b2f0e7b04286f8292b2479cb0e1f2f22d09c.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @dcci

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift-corelibs-foundation#1753
apple/swift#20329

@swift-ci please test

**Comment by dcci** [comment]
@compnerd feel free to go ahead :)

**Comment by compnerd** [comment]
@dcci - cool, will merge as soon as the dependent changes can be merged!

**Pull request merged**
