### PR TITLE
Use DeclNames instead of Identifiers in more places and consider special DeclNames

### PR DESCRIPTION
**Pull request by ahoppen**
This pull request must be merged simultaneously with [#5537](https://github.com/apple/swift/pull/5537) in the swift repository.

### CODE REVIEW

**Comment by tfiala** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/5537

@swift-ci Please test

**Comment by scallanan** [comment]
This looks all right to me assuming the underlying swift changes pass muster.

**Comment by ahoppen** [comment]
Yeah, the swift pull request is the main one and all these changes can't be adopted on their own.

**Comment by ahoppen** [comment]
Since the corresponding PR has been split up, I close this PR as well and create two smaller ones that correspond to the smaller PRs in the smaller Swift repo

**Pull request closed without merging**
