### PR TITLE
Support building DWARF-only (no .dSYM) Swift testcases

### PR DESCRIPTION
**Pull request by adrian-prantl**
rdar://problem/42977904

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by dcci** [comment]
@adrian-prantl out of curiosity, what was the problem?

**Comment by adrian-prantl** [comment]
I basically completely missed a linux-specific build rule: The -module-wrap pass. I do not understand how this could make it past PR testing.

**Comment by dcci** [comment]
Me neither. Are we running all the tests as part of PR testing?

**Comment by dcci** [comment]
(because at this point, we should)

**Comment by adrian-prantl** [comment]
There was some work on the Linux bots yesterday, perhaps they were temporarily turned off?

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift/pull/19442
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Pull request merged**
