### PR TITLE
API: resolve merge conflicts in the interface registry

### PR DESCRIPTION
**Pull request by compnerd**
The merge resolution resulted in a duplicated registry in the SBThread API and
an additional method in the SBThreadPlan.  Remove them to repair the build on
upstream-with-swift.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @JDevlieghere

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@JDevlieghere - mind taking a peek at the change here.  I believe that it is correct, but, I wouldn't mind a second pair of better eyes looking at this :)

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by JDevlieghere** [comment]
Sorry, yeah this looks correct. Not sure how I missed the existing registry calls when I did this merge...

**Pull request merged**
