### PR TITLE
Fix merge conflicts after D66737

### PR DESCRIPTION
**Pull request by Teemperor**

### CODE REVIEW

**Comment by Teemperor** [comment]
@swift-ci test

**Comment by dcci** [comment]
Thank you Raphael!

**Comment by dcci** [comment]
I think the failure is actually related to your PR

```

/Users/buildnode/jenkins/workspace/swift-lldb-PR-osx/lldb/source/Commands/CommandObjectExpression.cpp:671:18: error: assigning to 'lldb_private::Target *' from incompatible type 'lldb_private::Target'; take the address with &
        target = GetDummyTarget();
                 ^~~~~~~~~~~~~~~~
                 &
1 error generated.

```

**Comment by Teemperor** [comment]
@swift-ci test

**Pull request merged**
