### PR TITLE
Fix the SwiftSILManipulator for upstream changes.

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci Please test

**Comment by gottesmm** [comment]
I am just going to wait for the linux test to finish. If it passes, then I think it is safe to say that the OS X will as well, given how simple the change is.

**Comment by rudkx** [comment]
@gottesmm Can you add a test? Is there a reason this only hit under LLDB testing and not in the compiler tests?

**Comment by gottesmm** [comment]
No, I just forgot to update this given upstream changes. The assert that was hit here was the "test" that invariants were never broken. So this shows that the invariant asserts are working.

**Pull request merged**
