### PR TITLE
Merge llvm.org(master) into upstream-with-swift

### PR DESCRIPTION
**Pull request by dcci**

### CODE REVIEW

**Comment by dcci** [comment]
@xiaobai Alex, I'm under the impression your locking change should be on `stable` too. Do you agree?
On top, we should have a small modification in `swift-lldb` to make sure also the SwiftLanguageRuntime is locked. ACK/NACK? =)

**Comment by dcci** [comment]
[happy to do the work, just trying to collect your opinion here]

**Comment by bulbazord** [comment]
@dcci Yeah putting it on stable is a good idea I think. I don't understand what you mean by "make sure also the SwiftLanguageRuntime is locked". Does Process have its own field for a SwiftLanguageRuntime?

**Comment by dcci** [comment]
@xiaobai What I mean is, we should acquire a mutex in `GetSwiftLanguageRuntime` as we do in `GetCPPLanguageRuntime` and `GetObjCLanguageRuntime` right?

**Comment by bulbazord** [comment]
@dcci: Ah yes, I think that's the right thing to do.

**Pull request merged**
