### PR TITLE
build: normalise paths before use

### PR DESCRIPTION
**Pull request by compnerd**
Ensure that we normalise the paths to the CMake sytle paths before use.  If we
do not do this, we will fail to configure on Windows.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @dcci @adrian-prantl @JDevlieghere

**Comment by JDevlieghere** [comment]
Any reason this shouldn't live upstream?

**Comment by compnerd** [comment]
@JDevlieghere, yeah my reasoning for that is that the entire codepath that this is touching doesn't live upstream :-)  None of these variables are in the upstream build.

**Comment by JDevlieghere** [comment]
@compnerd Aight, I assumed this was the result of Stefan's change this morning and vaguely remembered him touching these paths, hence the question. Thanks for confirming, this LGTM.

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Pull request merged**
