### PR TITLE
Update for SE-0055: Making pointer nullability explicit.

### PR DESCRIPTION
**Pull request by jrose-apple**
See https://github.com/apple/swift/pull/1878. Sorry for not catching this pre-commit.

cc @egranata

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by egranata** [comment]
@scallanan Does the ASTManipulator part look right to you? If so, I am OK to merge (assuming tests pass)

**Comment by egranata** [comment]
I am testing locally this patch + an extra diff that cleans up string formatting (the string buffer is now an optional opaque pointer..)

Seems to be running cleanly for me - I will push my diff and close this PR if I get a clean run
We can iterate from there

**Comment by egranata** [comment]
commit fcb0ecbd3fb56def795a0da432ddae2feee6e9d0
Author: Enrico Granata <granata.enrico@gmail.com>
Date:   Tue Apr 12 12:36:31 2016 -0700

    Fix LLDB after the pointer nullability changes. Thanks to Jordan for putting most of this patch together

I'll keep an eye on the bots - but closing your PR for now since my diff is a superset

**Pull request closed without merging**
