### PR TITLE
[ExpressionSourceCode] Move Swift-only function SaveExpressionTextToTempFile to the Swift source.

### PR DESCRIPTION
**Pull request by Teemperor**

### CODE REVIEW

**Comment by Teemperor** [comment]
@swift-ci test

**Comment by Teemperor** [comment]
(the first commit is from #1949 where we remove the use of that function from the ClangExpressionParser)

**Review by adrian-prantl — APPROVED** [review]
That's a good idea!

**Review by dcci — APPROVED** [review]
LGTM

**Pull request merged**
