### PR TITLE
Stable with upstream cmake

### PR DESCRIPTION
**Pull request by weliveindetail**
All the upstream CMake changes that are missing on current stable (plus a few additional ones to avoid conflicts).

### CODE REVIEW

**Comment by weliveindetail** [comment]
@swift-ci please test

**Comment by weliveindetail** [comment]
I think this has a cyclic dependency with this change in Swift build-script https://github.com/apple/swift/pull/25931

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift/pull/25931
@swift-ci test

**Comment by weliveindetail** [comment]
test with apple/swift#25931
@swift-ci test

**Comment by weliveindetail** [comment]
test with apple/swift#25931
@swift-ci test

**Pull request merged**
