### PR TITLE
[CMake] Use NO_CMAKE_FIND_ROOT_PATH when finding clang, llvm, and swift

### PR DESCRIPTION
**Pull request by bulbazord**
When you cross-compile or specify a custom sysroot, it is possible that
the CMake toolchain files will set CMAKE_FIND_ROOT_PATH and set
CMAKE_FIND_ROOT_PATH_MODE_* VARIABLES to ONLY, so packages will only be
searched in a rerooted setting. This is an issue when we search for
clang, llvm, and swift, because we are usually passing them explicitly with
LLDB_PATH_TO_{CLANG,LLVM,SWIFT}_BUILD and do not want these paths to be
rerooted.

### CODE REVIEW

**Comment by bulbazord** [comment]
cc @dcci @compnerd @adrian-prantl

**Comment by dcci** [comment]
@swift-ci please test

**Comment by bulbazord** [comment]
@dcci: Is this good to go?

**Review by dcci — APPROVED** [review]
LGTM.

**Comment by dcci** [comment]
feel free to merge this.

**Pull request merged**
