### PR TITLE
Extract additional triple details from serialized Swift ASTs.

### PR DESCRIPTION
**Pull request by alblue**
Unfortunately things like the vendor name can affect Swift's ability
to find the correct stdlib.

Backported for Linux fix from `bf4f8fe` for Swift 5.1.4

<rdar://problem/45766181>

### CODE REVIEW

**Comment by alblue** [comment]
This is a backport of #2060

**Comment by kevints** [comment]
@swift-ci please test 5.1

**Comment by alblue** [comment]
@adrian-prantl can you kick off tests and merge as necessary?

**Comment by kevints** [comment]
It looks like this was already back-ported in https://github.com/apple/llvm-project/commit/2079772a6616ef13e91e606f2d8aaa49f4fd2f21

**Review by dcci — CHANGES_REQUESTED** [review]
This patch is already on the 5.1 branch apparently.

**Pull request closed without merging**
