### PR TITLE
Remove eLanguageFlag which is not used anywhere

### PR DESCRIPTION
**Pull request by Teemperor**

### CODE REVIEW

**Comment by Teemperor** [comment]
@swift-ci test

**Comment by Teemperor** [comment]
Seems like it's only unused in upstream-with-swift and the thing was introduced in some swift-only clang refactoring in 5f3aa16203d308773108c4d03ed4d4ec8e4a47c2

**Comment by dcci** [comment]
We should see whether we can get rid of that.

**Comment by Teemperor** [comment]
Yeah, it seems that was done to kind of allow some form of unified setting thing between Clang and Swift. Working on it.

**Pull request closed without merging**
