### PR TITLE
Add a test for swift split debug-info

### PR DESCRIPTION
**Pull request by fjricci**
Re-upload of https://github.com/apple/swift-lldb/pull/289 onto upstream-with-swift, rebasing past buildbot failures (at least the macOS ones, looks like linux may still be failing).

### CODE REVIEW

**Comment by fjricci** [comment]
@swift-ci please test

**Comment by fjricci** [comment]
Looks like master (or whatever the README links to) is still red. @dcci - Not sure how to proceed here. I have this patch, #288, plus another bug fix in preparation locally.

**Comment by dcci** [comment]
@fjricci we finally got our stuffs together and we agreed that the flow is that of pushing to stable and then up porting to `upstream-with-swift`. Feel free to rebase/change the branch to which this PR points to, and run test & merge again. (hopefully all the outstanding issues should be sorted out, crossing fingers).

Thanks!

**Comment by fjricci** [comment]
will re-open against stable

**Pull request closed without merging**
