### PR TITLE
Cherry-pick breakpoint changes from llvm.org

### PR DESCRIPTION
**Pull request by bulbazord**
I'm cherry-picking the following 2 changes from llvm.org to make merging into upstream-with-swift easier. The first commit in the stack has already landed upstream, the second I intend to land later today.

### CODE REVIEW

**Comment by bulbazord** [comment]
cc @jimingham @JDevlieghere

**Review by JDevlieghere — APPROVED** [review]

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test linux

**Comment by JDevlieghere** [comment]
@swift-ci please test linux

**Comment by JDevlieghere** [comment]
@swift-ci please test linux

**Comment by JDevlieghere** [comment]
@swift-ci please test macos

**Pull request merged**
