### PR TITLE
Only load dependent files for executables

### PR DESCRIPTION
**Pull request by JDevlieghere**
Unless explicitly requested, only load dependent files when the target is an executable.

rdar://problem/43721382

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci please test and merge

**Comment by JDevlieghere** [comment]
@swift-ci please test and merge

**Comment by JDevlieghere** [comment]
@swift-ci please test and merge

**Comment by adrian-prantl** [comment]
It looks like this broke the bots. I'll try reverting.
https://ci.swift.org/job/oss-lldb-osx/2739/

**Pull request merged**
