### PR TITLE
Reapply merge from llvm.org lldb svn trunk, r260951, with fixes

### PR DESCRIPTION
**Pull request by tfiala**
@swift-ci Please test OS X platform

This change restores the merge from llvm.org from Friday, plus
fixes up all the test issues that failed to run and were not
caught by changes to the test infrastructure upstream.

This change enhances the lldb inline test mechanism to only
run debuginfo variants that make sense for the platform.
Previously it always ran all of them.

This change only addresses issues on OS X.  A follow-up commit
will be made to address known-to-exist Linux issues.  I want
to run this change by the OS X pull request testing on the
Swift LLDB CI first, though.

This reverts commit 0c0701210828a9280d4ded63b087efc9cc74003a.

### CODE REVIEW

**Comment by tfiala** [comment]
@swift-ci Please test OS X platform

**Comment by tfiala** [comment]
The first-time run of the PR build machinery as configured for LLDB is hitting an internal failure.  I'm checking if I can get that resolved...

**Comment by tfiala** [comment]
@swift-ci Please test Linux platform

**Comment by tfiala** [comment]
I'm having the Linux build tested.  I have it building now, but I'd like that verified by CI.  Also, I am seeing quite a few test failures on Linux that I will need to track down.  I just want to see if there are any discrepancies on the CI vs. what I'm seeing locally.

**Comment by gribozavr** [comment]
@swift-ci Please test Linux platform

**Comment by gribozavr** [comment]
@swift-ci Please test Linux platform

**Comment by gribozavr** [comment]
@tfiala I have fixed the configuration, the build is running now.

**Comment by tfiala** [comment]
@gribozavr - thanks!

**Comment by tfiala** [comment]
The CI Linux build is matching what I was seeing locally:

ERROR: testREPL (repl/recursive_class/TestREPLRecursiveClass.py)
ERROR: testREPL (repl/quicklookobject/TestREPLQuickLookObject.py)
ERROR: testREPL (repl/pounwrapping/TestPOUnwrapping.py)
ERROR: testREPL (repl/lazy_reverse/TestLazyReverse.py)
ERROR: testREPL (repl/basic/TestREPLBasic.py)
ERROR: testREPL (repl/func_definition/TestREPLFunctionDefinition.py)
ERROR: testREPL (repl/multilevelarrays/TestMultilevelArrays.py)
ERROR: testREPL (repl/closures/TestREPLClosure.py)
ERROR: testREPL (repl/dictionary/TestREPLDictionary.py)
ERROR: test_dwarf (functionalities/data-formatter/data-formatter-stl/libcxx/atomic/TestLibCxxAtomic.py)
ERROR: test_dwo (functionalities/data-formatter/data-formatter-stl/libcxx/atomic/TestLibCxxAtomic.py)
ERROR: [EXCEPTIONAL EXIT 11 (SIGSEGV)] test_in_out_variables_dwarf (lang/swift/variables/inout/TestInOutVariables.py)
ERROR: [EXCEPTIONAL EXIT 11 (SIGSEGV)] test_ivars_in_generic_expressions_dwarf (lang/swift/expression/generic/TestSwiftGenericExpressions.py)
ERROR: [EXCEPTIONAL EXIT 11 (SIGSEGV)] test_simple_swift_expressions_dwarf (lang/swift/expression/simple/TestSimpleExpressions.py)
ERROR: [EXCEPTIONAL EXIT 11 (SIGSEGV)] test_swift_stdlib_dictionary_dwarf (lang/swift/variables/dictionary/TestSwiftStdlibDictionary.py)
ERROR: [EXCEPTIONAL EXIT 11 (SIGSEGV)] test_swift_type_lookup_dwarf (lang/swift/printdecl/TestSwiftTypeLookup.py)
ERROR: [EXCEPTIONAL EXIT 11 (SIGSEGV)] test_with_dwarf (lang/swift/po_recursive/TestSwiftPORecursiveBehavior.py)
ERROR: [EXCEPTIONAL EXIT 11 (SIGSEGV)] test_with_dwarf (lang/swift/variables/generic_struct_debug_info/generic_array/TestSwiftGenericStructDebugInfoGenericArray.py)
ERROR: [EXCEPTIONAL EXIT 11 (SIGSEGV)] test_with_dwarf (lang/swift/po/val_types/TestSwiftPOValTypes.py)
ERROR: [EXCEPTIONAL EXIT 11 (SIGSEGV)] test_with_dwarf (lang/swift/variables/generic_struct_debug_info/generic_flatmap/TestSwiftGenericStructDebugInfoGenericFlatMap.py)
ERROR: [EXCEPTIONAL EXIT 11 (SIGSEGV)] test_with_dwarf (lang/swift/po/ref_types/TestSwiftPORefTypes.py)
ERROR: [EXCEPTIONAL EXIT 11 (SIGSEGV)] test_with_dwarf (lang/swift/variables/generic_struct_debug_info/generic_apply/TestSwiftGenericStructDebugInfoGenericApply.py)

I'm going to try to knock those out today.

**Comment by tfiala** [comment]
@swift-ci Please test OS X platform

**Comment by tfiala** [comment]
Hey Dmitri - are you able to see the OS X pull request builders?  We had a similar problem there where it failed to kick off the build after the code sync.  Also, it seemed to ignore my request a couple hours ago to build the OS X side.

**Comment by tfiala** [comment]
@swift-ci Please test OS X platform

**Comment by tfiala** [comment]
The LLDB OS X Pull Request infrastructure is still not functioning correctly.  It bails after syncing source.

**Comment by tfiala** [comment]
Checking the Linux build after the seg fault fixup.

@swift-ci Please test Linux platform

**Comment by tfiala** [comment]
@swift-ci Please test Linux platform

**Comment by tfiala** [comment]
Fixing the segfault on Ubuntu 15.10 x86_64 gets us to a still-broken but less extreme set of issues (no more lldb crashes):

```
=============
Issue Details
=============
FAIL: test_in_out_variables_dwarf (lang/swift/variables/inout/TestInOutVariables.py)
FAIL: test_in_out_variables_dwo (lang/swift/variables/inout/TestInOutVariables.py)
FAIL: test_ivars_in_generic_expressions_dwarf (lang/swift/expression/generic/TestSwiftGenericExpressions.py)
FAIL: test_ivars_in_generic_expressions_dwo (lang/swift/expression/generic/TestSwiftGenericExpressions.py)
FAIL: test_simple_swift_expressions_dwarf (lang/swift/expression/simple/TestSimpleExpressions.py)
FAIL: test_simple_swift_expressions_dwo (lang/swift/expression/simple/TestSimpleExpressions.py)
FAIL: test_swift_stdlib_dictionary_dwarf (lang/swift/variables/dictionary/TestSwiftStdlibDictionary.py)
FAIL: test_swift_stdlib_dictionary_dwo (lang/swift/variables/dictionary/TestSwiftStdlibDictionary.py)
FAIL: test_swift_type_lookup_dwarf (lang/swift/printdecl/TestSwiftTypeLookup.py)
FAIL: test_swift_type_lookup_dwo (lang/swift/printdecl/TestSwiftTypeLookup.py)
FAIL: test_with_dwarf (lang/swift/po_recursive/TestSwiftPORecursiveBehavior.py)
FAIL: test_with_dwarf (lang/swift/variables/generic_struct_debug_info/generic_array/TestSwiftGenericStructDebugInfoGenericArray.py)
FAIL: test_with_dwarf (lang/swift/po/val_types/TestSwiftPOValTypes.py)
FAIL: test_with_dwarf (lang/swift/variables/generic_struct_debug_info/generic_flatmap/TestSwiftGenericStructDebugInfoGenericFlatMap.py)
FAIL: test_with_dwarf (lang/swift/po/ref_types/TestSwiftPORefTypes.py)
FAIL: test_with_dwarf (lang/swift/variables/generic_struct_debug_info/generic_apply/TestSwiftGenericStructDebugInfoGenericApply.py)
FAIL: test_with_dwo (lang/swift/variables/generic_struct_debug_info/generic_apply/TestSwiftGenericStructDebugInfoGenericApply.py)
FAIL: test_with_dwo (lang/swift/variables/generic_struct_debug_info/generic_array/TestSwiftGenericStructDebugInfoGenericArray.py)
FAIL: test_with_dwo (lang/swift/variables/generic_struct_debug_info/generic_flatmap/TestSwiftGenericStructDebugInfoGenericFlatMap.py)
FAIL: test_with_dwo (lang/swift/po_recursive/TestSwiftPORecursiveBehavior.py)
FAIL: test_with_dwo (lang/swift/po/ref_types/TestSwiftPORefTypes.py)
FAIL: test_with_dwo (lang/swift/po/val_types/TestSwiftPOValTypes.py)
ERROR: testREPL (repl/quicklookobject/TestREPLQuickLookObject.py)
ERROR: testREPL (repl/pounwrapping/TestPOUnwrapping.py)
ERROR: testREPL (repl/lazy_reverse/TestLazyReverse.py)
ERROR: testREPL (repl/basic/TestREPLBasic.py)
ERROR: testREPL (repl/func_definition/TestREPLFunctionDefinition.py)
ERROR: testREPL (repl/multilevelarrays/TestMultilevelArrays.py)
ERROR: testREPL (repl/closures/TestREPLClosure.py)
ERROR: testREPL (repl/dictionary/TestREPLDictionary.py)
ERROR: test_dwarf (functionalities/data-formatter/data-formatter-stl/libcxx/atomic/TestLibCxxAtomic.py)
ERROR: test_dwo (functionalities/data-formatter/data-formatter-stl/libcxx/atomic/TestLibCxxAtomic.py)
```

**Comment by gribozavr** [comment]
@swift-ci Please test OS X platform

**Comment by gribozavr** [comment]
@tfiala Fixed it!

**Comment by tfiala** [comment]
@gribozavr - thanks, Dmitri!

**Comment by tfiala** [comment]
Sean Callanan and I are working on the Ubuntu 15.10 side this morning.  Hope to have this resolved soon.

**Comment by tfiala** [comment]
We've cleaned up a number of the Ubuntu 15.10 issues with 15284c99138f58c49cea68c91b28a1f7fc449f78.  Verifying ci.swift.org Linux builder concurs that we're down from ~32 to ~13 issues now.

**Comment by tfiala** [comment]
@swift-ci Please test

**Comment by tfiala** [comment]
Ah well now this is very interesting - with top of tree github swift-lldb against latest swift-clang, swift-llvm and swift, we are now getting 10 of these 13 failures.  (i.e. 10 of these are failing with swift-lldb master against latest swift master, clang stable and llvm stable):

```
FAIL: test_dwarf (functionalities/watchpoint/step_over_watchpoint/TestStepOverWatchpoint.py)
FAIL: test_dwo (functionalities/watchpoint/step_over_watchpoint/TestStepOverWatchpoint.py)
FAIL: test_generic_expressions_dwarf (lang/swift/expression/generic/TestSwiftGenericExpressions.py)
FAIL: test_generic_expressions_dwo (lang/swift/expression/generic/TestSwiftGenericExpressions.py)
FAIL: test_genericresolution_commands_dwarf (lang/swift/generics/TestSwiftGenericsResolution.py)
FAIL: test_genericresolution_commands_dwo (lang/swift/generics/TestSwiftGenericsResolution.py)
FAIL: test_ivars_in_generic_expressions_dwarf (lang/swift/expression/generic/TestSwiftGenericExpressions.py)
FAIL: test_ivars_in_generic_expressions_dwo (lang/swift/expression/generic/TestSwiftGenericExpressions.py)
ERROR: [EXCEPTIONAL EXIT 6 (SIGABRT)] test_expressions_in_class_functions_dwarf (lang/swift/expression/static/TestSwiftExpressionsInClassFunctions.py)
ERROR: [EXCEPTIONAL EXIT 6 (SIGABRT)] test_with_dwarf (lang/swift/partially_generic_func/class/TestSwiftPartiallyGenericFuncClass.py)
```

Jim Ingham, Adrian Prantl and I looked into the generics test issues.  We've got bad line table content for the Swift generics metadata setup code - the setup calls haven't completed by the first valid line within a function.  Thus, the type information is not known when it should be on Ubuntu 15.10.  This is happening irrespective of the swift-lldb code as it is a line table generation issue.

I'm going to mark the ones failing as XFAIL blocked on the code generation bug.

This leaves us with these failures unique to the merge on Ubuntu 15.10:
```
ERROR: test_dwarf (functionalities/data-formatter/data-formatter-stl/libcxx/atomic/TestLibCxxAtomic.py)
ERROR: test_dwo (functionalities/data-formatter/data-formatter-stl/libcxx/atomic/TestLibCxxAtomic.py)
ERROR: testREPL (repl/pounwrapping/TestPOUnwrapping.py)
```
I'm going to verify what I am seeing locally on the builders, get those errors marked up and blocked on some JIRA tickets, pull in the xfails, and work on the remaining merge-specific issues.

**Comment by DougGregor** [comment]
@rjmccall can describe what's changed with code generation

**Comment by tfiala** [comment]
Thanks, Doug!

**Comment by tfiala** [comment]
I just put up a change to swift-lldb master to clean up the Ubuntu failures here:
96dc9d5a4d5e0ac46c1b4d7ec9766a587e2ab810

(After reverting some other changes from earlier in the day on the swift repo that were breaking the LLDB build).

Once I get confirmation that the Ubuntu builds are back to green, I'll pull them into the merge branch here and see what's left that's newly broken by the merge, and get those fixed up.

**Comment by tfiala** [comment]
After merging in the "get the Ubuntu CI green" change above, I'm locally seeing only 3 remaining failures related to the merge on Ubuntu 15.10.  Testing that with the CI next.

**Comment by tfiala** [comment]
@swift-ci Please test

**Comment by tfiala** [comment]
Build check on Ubuntu 14.04 verified what I'm seeing.  I'm looking into those 3 merge-specific, Ubuntu-specific issues:
```
ERROR: testREPL (repl/pounwrapping/TestPOUnwrapping.py)
ERROR: test_dwarf (functionalities/data-formatter/data-formatter-stl/libcxx/atomic/TestLibCxxAtomic.py)
ERROR: test_dwo (functionalities/data-formatter/data-formatter-stl/libcxx/atomic/TestLibCxxAtomic.py)
```

**Comment by tfiala** [comment]
Investigated test failures.  Two should have been skipped wholesale - they were trying to use libc++ under the premise that when there's clang, there's libc++ (false).  The other requires somebody to look into, but isn't catastrophic and shouldn't hold the merge.  (Optionals that are nil getting printed as 0/empty string on Linux).  Bug filed for it.

**Comment by tfiala** [comment]
@swift-ci Please test

**Comment by tfiala** [comment]
@swift-ci Please test

**Pull request merged**
