### PR TITLE
Update for change to VisibleDeclConsumer

### PR DESCRIPTION
**Pull request by benlangmuir**
Match change in https://github.com/apple/swift/pull/24520

### CODE REVIEW

**Comment by benlangmuir** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/24520

@swift-ci please smoke test

**Comment by benlangmuir** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/24520

@swift-ci please test

**Comment by benlangmuir** [comment]
Please test with following pull request:
apple/swift#24520

@swift-ci please test

**Review by dcci — APPROVED** [review]
LGTM.

**Pull request merged**
