### PR TITLE
disable data tests until SR-3320 can be addressed

### PR DESCRIPTION
**Pull request by phausler**

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by tfiala** [comment]
@swift-ci Please test and merge

**Comment by tfiala** [comment]
@swift-ci Please test and merge

**Comment by tfiala** [comment]
@swift-ci Please test

**Comment by tfiala** [comment]
(We'll do the merge separately)

**Comment by tfiala** [comment]
Hi @phausler, Jim Ingham is going to check in the fix for this.  The way it is written here a Python syntax error in it:
```
Traceback (most recent call last):
  File "/home/buildnode/jenkins/workspace/swift-lldb-PR-Linux@3/branch-master/lldb/test/dotest.py", line 7, in <module>
    lldbsuite.test.run_suite()
  File "/home/buildnode/jenkins/workspace/swift-lldb-PR-Linux@3/branch-master/lldb/packages/Python/lldbsuite/test/dotest.py", line 1171, in run_suite
    visit('Test', dirpath, filenames)
  File "/home/buildnode/jenkins/workspace/swift-lldb-PR-Linux@3/branch-master/lldb/packages/Python/lldbsuite/test/dotest.py", line 911, in visit
    visit_file(dir, name)
  File "/home/buildnode/jenkins/workspace/swift-lldb-PR-Linux@3/branch-master/lldb/packages/Python/lldbsuite/test/dotest.py", line 881, in visit_file
    unittest2.defaultTestLoader.loadTestsFromName(base))
  File "/home/buildnode/jenkins/workspace/swift-lldb-PR-Linux@3/branch-master/lldb/third_party/Python/module/unittest2/unittest2/loader.py", line 105, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/buildnode/jenkins/workspace/swift-lldb-PR-Linux@3/branch-master/lldb/packages/Python/lldbsuite/test/lang/swift/foundation_value_types/data/TestSwiftFoundationTypeData.py", line 18
    decorators.expectedFailureAll(bugnumber="https://bugs.swift.org/browse/SR-3320")])])
                                                                                      ^
SyntaxError: invalid syntax
```

We'll close this out once Jim's change goes in.

**Comment by tfiala** [comment]
Hi @phausler,

I think Jim checked in the fix for this.  Can you confirm and close this PR out?

Thanks!

**Pull request closed without merging**
