### PR TITLE
[SwiftLanguageRuntime] Remove unused helpers.

### PR DESCRIPTION
**Pull request by dcci**
This opens the path for more simplification in this file.

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci test and merge

**Comment by dcci** [comment]
@swift-ci please test

**Comment by vedantk** [comment]
Should the method declarations be deleted as well?

**Comment by dcci** [comment]
yes, they should, thanks for noticing.

**Comment by dcci** [comment]
Addressed Vedant's comments.

**Review by vedantk — APPROVED** [review]
Thanks!

**Review by JDevlieghere — APPROVED** [review]
LGTM!

**Comment by dcci** [comment]
@swift-ci please test and merge

**Comment by dcci** [comment]
@shahmishal  ping me once you enable the `test and merge` feature for `swift-lldb`, I'll use this PR as guinea pig to make sure it works.

**Comment by dcci** [comment]
@swift-ci please test

**Comment by dcci** [comment]
@swift-ci please test

**Pull request merged**
