### PR TITLE
[4.0] Add SwiftRuntimeReporting instrumentation plugin to receive runtime issues from the Swift language runtime

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by vedantk** [comment]
If there aren't any changes in this patch between swift-4.0-branch and stable, I think it just needs to be committed to swift-4.0-branch, since that (iirc) gets auto merged into stable.

@kubamracek On another note, am I required to use the "Approve" UI here? This has a textual 'lgtm' from #213.

**Comment by kubamracek** [comment]
We can land the patch in stable without the need for approval, so let's keep two pull requests for now.  I'll double check what the usual process is.

In the meantime, if you don't have comments, could you actually use the "Approve" button to mark this as reviewed?  It's needed to satisfy the swift-4.0-branch merging process.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by vedantk — APPROVED** [review]
LGTM.

**Pull request merged**
