### PR TITLE
Switch hard-coded CountableRange in test to be type Range

### PR DESCRIPTION
**Pull request by airspeedswift**
To match the elimination of the type (except for a compatibility alias) done in apple/swift#13342

### CODE REVIEW

**Comment by airspeedswift** [comment]
Not sure if the tests would be better refactored to eliminate some duplication that is only there because there used to be two types.

**Comment by airspeedswift** [comment]
And then at some point, we can remove the other references to `CountableRange` completely... but wanted to fix this test quickly first.

**Comment by vedantk** [comment]
Thanks for the patch! After applying it locally, I am seeing a failure in the test:
'frame variable c' returns expected result, got '(CountableClosedRange<Int>) c = 1...100'

Is this something you can reproduce locally? Either way, I'll rebase and test again.

**Comment by jimingham** [comment]
This looks fine to me.  Since "..." and "..<" are two different user gestures to make ranges it seems worthwhile testing both, even if we know under the covers they are the same.

You mentioned having a "compatibility alias" for CountableRange.  If we ran across a type that wasspecified with that alias, that will trigger the data formatter for CountableRange.  Presumably now that is going to print an incorrect value so we really do need to remove the data formatter as well.  Then the formatter matching will fall back to the type that the alias points to (presumably Range) which will do the right thing.

Depending on how long the CountableRange type alias is going to hang around we might want to add a test for that as well.

But I'm fine with doing that as a follow-up task.

**Review by jimingham — APPROVED** [review]
This is fine as a fix to the testsuite.

We do need to remove the stale formatters (both CountableRange & CountableClosedRange, right?) since they might trigger and return the wrong result.

**Review by vedantk — CHANGES_REQUESTED** [review]
I'd like some more time to test this.

**Comment by airspeedswift** [comment]
@vedantk I only landed the switch for `someInt..<someInt` to return a regular not countable range last night, so you may need to pull and rebuild from latest master.

**Comment by vedantk** [comment]
Thanks @airspeedswift, after rebasing the test LGTM! I do have one more change to request. Could you add "@decorators.add_test_categories(["swiftpr"])" below "@decorators.swiftTest"? That way, this test can run as a part of pull-request testing for Swift.

**Review by dcci — APPROVED** [review]
LGTM if Vedant is happy/done with his testing.
Thank you @airspeedswift !

**Comment by vedantk** [comment]
The test looks good, but it'd be nice to have this in the `swiftpr` testing category.

**Comment by airspeedswift** [comment]
@vedantk done!

**Review by vedantk — APPROVED** [review]

**Comment by vedantk** [comment]
Thank you @airspeedswift! @shahmishal could you force-merge this please?

**Comment by vedantk** [comment]
I’m not sure why my merge dropped Ben’s last change, I’ll just have to add it back in later.

**Comment by airspeedswift** [comment]
I think it's still there, just that GitHub isn't showing it in the Files Changed view?  ¯\\\_(ツ)_/¯

**Comment by vedantk** [comment]
You're right, I must have added in the decorator yesterday.

**Pull request merged**
