### PR TITLE
Target: use the secondary host build of swiftReflection

### PR DESCRIPTION
**Pull request by compnerd**
Adjust for the new host build of the swiftReflection library for the tools.

### CODE REVIEW

**Comment by compnerd** [comment]
Please test with following PR:
https://github.com/apple/swift/pull/20156

@swift-ci please test

**Comment by gottesmm** [comment]
This cmake looks good to me. @dcci your thoughts?

**Comment by dcci** [comment]
If this doesn't break anything, I'm very happy to see it going in :)

**Review by dcci — APPROVED** [review]

**Comment by dcci** [comment]
Please keep an eye on the bots, though ... linking swiftReflection has been source of issues in the past (sometimes not caught by PR testing).

**Comment by gottesmm** [comment]
@dcci It shouldn't make a difference. What we are doing here is compiling swiftReflection for host separately from the target one. So there may be a broken build due to automergers/etc, if lldb merges before swift downstream, but once that resolves, this should be much better.

**Comment by dcci** [comment]
I agree. Let me merge this one :)

**Pull request merged**
