### PR TITLE
Reflect linux

### PR DESCRIPTION
**Pull request by zisko**
Re-adding these changes to make lldb link against reflection

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci please clean test

**Comment by dcci** [comment]
@swift-ci please test macos

**Comment by dcci** [comment]
@adrian-prantl it's unclear how this passed PR testing, as Jacob did all the diligency work of testing it. I guess we need to look at this closely.

**Comment by zisko** [comment]
I rebased this after you triggered a test, we may need to re-trigger!

**Comment by dcci** [comment]
@swift-ci please clean test

**Comment by shahmishal** [comment]
@swift-ci please clean test macOS

**Comment by shahmishal** [comment]
@swift-ci please test macOS

**Comment by shahmishal** [comment]
@swift-ci please test macOS

**Comment by shahmishal** [comment]
LLDB PR testing does clean build, so we dont need to request `@swift-ci clean test macOS`

**Comment by vivkong** [comment]
This is causing the build to fail on Linux on Z (s390x).

**Comment by adrian-prantl** [comment]
@vivkong How exactly did it fail? Is there a bot with a log somewhere?

**Comment by vivkong** [comment]
Sorry I should've left more details - on s390x we won't have `swiftReflection-linux-x86_64`

```
01:44:22 /opt/binutils-2.27/bin/ld: cannot find -lswiftReflection-linux-x86_64
```

Need to do the same lookup on Linux like we already did on Darwin?

**Comment by dcci** [comment]
@vivkong you might consider special casing this then? 
I don't have a `Linux-s390x` machine to test on, I'm afraid.
Please ping me if you need any help.

**Comment by mundaym** [comment]
I've sent #962 which fixes the Linux on Z issue, reviews would be greatly appreciated. Thanks.

**Pull request merged**
