### PR TITLE
Add an SBExpressionOptions setting mirroring the "exec" command's --a…

### PR DESCRIPTION
**Pull request by jimingham**
…llow-jit.

<rdar://problem/44809176>

Differential Revision: https://reviews.llvm.org/D54056

git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@346053 91177308-0d34-0410-b5e6-96231b3b80d8

### CODE REVIEW

**Comment by jimingham** [comment]
@swift-ci please test and merge

**Comment by dcci** [comment]
This seems to have caused a failure on the bots because the API is not there. I'll update this manually but clearly we should consider installing swig on the bots.

```
08:16:59 Traceback (most recent call last):
08:16:59   File "/Users/buildnode/jenkins/workspace/oss-lldb-incremental-osx-cmake/lldb/packages/Python/lldbsuite/test/decorators.py", line 114, in wrapper
08:16:59     func(*args, **kwargs)
08:16:59   File "/Users/buildnode/jenkins/workspace/oss-lldb-incremental-osx-cmake/lldb/packages/Python/lldbsuite/test/expression_command/dont_allow_jit/TestSampleTest.py", line 37, in test_allow_jit_options
08:16:59     self.expr_options_test()
08:16:59   File "/Users/buildnode/jenkins/workspace/oss-lldb-incremental-osx-cmake/lldb/packages/Python/lldbsuite/test/expression_command/dont_allow_jit/TestSampleTest.py", line 69, in expr_options_test
08:16:59     self.assertEqual(options.GetAllowJIT(), True, "Default is true")
08:16:59   File "/Users/buildnode/jenkins/workspace/oss-lldb-incremental-osx-cmake/Ninja-ReleaseAssert+stdlib-Release/lldb-macosx-x86_64/Library/Frameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 4375, in <lambda>
08:16:59     __getattr__ = lambda self, name: _swig_getattr(self, SBExpressionOptions, name)
08:16:59   File "/Users/buildnode/jenkins/workspace/oss-lldb-incremental-osx-cmake/Ninja-ReleaseAssert+stdlib-Release/lldb-macosx-x86_64/Library/Frameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 79, in _swig_getattr
08:16:59     raise AttributeError(name)
08:16:59 AttributeError: GetAllowJIT
08:16:59 Config=x86_64-/Users/buildnode/jenkins/workspace/oss-lldb-incremental-osx-cmake/Ninja-ReleaseAssert+stdlib-Release/llvm-macosx-x86_64/bin/clang-7
```

**Comment by clayborg** [comment]
Did someone forget to update the .i file?

**Comment by dcci** [comment]
Attempt to fix here: https://github.com/apple/swift-lldb/pull/1031

**Pull request merged**
