### PR TITLE
Merge into stable: [lldb] Add support for "external" reports in ThreadSanitizer LLDB plugin

### PR DESCRIPTION
**Pull request by kubamracek**
TSan now has the ability to report races on "external" object, i.e. any library class/object that has read-shared write-exclusive threading semantics. The detection and reporting work almost out of the box, but TSan can now provide the type of the object (as a string). This patch implements this into LLDB.

Differential Revision: https://reviews.llvm.org/D30024

git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@295342 91177308-0d34-0410-b5e6-96231b3b80d8

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by dcci** [comment]
@kubamracek is this one still relevant?

**Comment by kubamracek** [comment]
@dcci No, looks like this is already in via a rebranch. Closing.

**Pull request closed without merging**
