### PR TITLE
Cherry-pick "Add a case in SymbolFile{Native,}PDB::TranslateLanguage for Swift" from llvm.org/master

### PR DESCRIPTION
**Pull request by lanza**
Summary: see above

Reviewers: compnerd

Differential Revision: https://reviews.llvm.org/D59230

git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@355883 91177308-0d34-0410-b5e6-96231b3b80d8

### CODE REVIEW

**Comment by lanza** [comment]
@compnerd

**Comment by compnerd** [comment]
This needs apple/swift-llvm#143 to be merged first.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@adrian-prantl - okay with this?  Should not impact non-Windows targets

**Pull request merged**
