### PR TITLE
[Swift] Add a test for generalized accessors basic functionality.

### PR DESCRIPTION
**Pull request by dcci**
<rdar://problem/43578347>

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci test and merge

**Comment by jrose-apple** [comment]
Sorry, how does this test generalized accessors?

**Comment by dcci** [comment]
@jrose-apple They're tested through Dictionary subscript _modify. I might consider adding something more direct as a follow-up.

**Comment by jrose-apple** [comment]
But you don't stop inside the accessor or anything. This is just "run some code, then break, then run some more code". It doesn't matter that the code before or after is a generalized accessor.

**Comment by dcci** [comment]
cc: @airspeedswift (who actually crafted the test case for us in the debugger and explained to me how this works).

My understanding is that accessors modify how `double()` behave.
Before:
`subscript get` returns a copy of the array, the function modifies it, and `subscript set` replaces the old value with the new one (triggering CoW).

After:
`subscript _modify` moves the array into the optional, and so the array should be unique and will be modified without triggering CoW. Then after the yield, it’s moved back.

So, this is just testing that lldb behaves correctly during the yield. Am I missing something here?

**Comment by jrose-apple** [comment]
The "during the yield" part is the part I'm suspicious of. You stopped on a line, not at a particular expression, so the access won't have started yet.

**Comment by dcci** [comment]
I see your point. What about something modeled after what's in the test suite?

```
private var backingX = 0
var x: Int {
  _read {
    yield backingX
    backingX += 1
  }
  _modify {
    var temp = backingX
    yield &temp
    if temp >= backingX {
      backingX = temp
    }   
  }
}

print(x)
x += 10
print (x)
x -= 20
```

At that point I can stop on the `yield` line or anywhere in modify and make sure the value printed is correct.

**Comment by jrose-apple** [comment]
That seems reasonable to me. You should also be able to print *other* parts of the struct besides the backing.

**Pull request merged**
