### PR TITLE
Adjust for SVN r367392

### PR DESCRIPTION
**Pull request by compnerd**
Adjust the Swift for for the renamed member variable in SVN r367392

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @dcci @JDevlieghere @xiaobai

**Comment by compnerd** [comment]
@swift-ci please test

**Review by bulbazord — APPROVED** [review]

**Review by dcci — APPROVED** [review]

**Comment by dcci** [comment]
Still seems to fail

```
15:01:06 /Users/buildnode/jenkins/workspace/swift-lldb-PR-osx/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARF.cpp:3070:22: error: use of undeclared identifier 'm_objfile_sp'
15:01:06   ModuleSP module_sp(m_objfile_sp->GetModule());
```

**Comment by bulbazord** [comment]
> Still seems to fail
> 
> ```
> 15:01:06 /Users/buildnode/jenkins/workspace/swift-lldb-PR-osx/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARF.cpp:3070:22: error: use of undeclared identifier 'm_objfile_sp'
> 15:01:06   ModuleSP module_sp(m_objfile_sp->GetModule());
> ```

I think the merge needs to go in first.

**Pull request closed without merging**
