### PR TITLE
Remove an errant ^S

### PR DESCRIPTION
**Pull request by jimingham**
(still can't get over those Emacs habits...)

git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@324509 91177308-0d34-0410-b5e6-96231b3b80d8

### CODE REVIEW

**Comment by jimingham** [comment]
@swift-ci please test and merge

**Comment by dcci** [comment]
@jimingham test and merge isn't yet implemented (on @shahmishal TODOlist).
For the time being, I think you can just do `@swift-ci please test` and then click the button yourself.

**Comment by jimingham** [comment]
@swift-ci please test

**Comment by jimingham** [comment]
Thanks!

**Pull request merged**
