### PR TITLE
Watchpoint commands

### PR DESCRIPTION
**Pull request by jimingham**
Fix a bug where watchpoint commands which continue the process do so with the watchpoint disabled.

### CODE REVIEW

**Comment by jimingham** [comment]
@swift-ci Please test

**Comment by jimingham** [comment]
@swift-ci Please test

**Comment by jimingham** [comment]
@swift-ci Please test

**Comment by jimingham** [comment]
@swift-ci Please test

**Comment by jimingham** [comment]
@swift-ci Please test

**Comment by jimingham** [comment]
@swift-ci Please test

**Comment by tfiala** [comment]
@swift-ci Please test

**Pull request merged**
