### PR TITLE
Simplify testcase

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Review by jimingham — APPROVED** [review]
This looks nicer.  If you use run_to_source_breakpoint you don't need to check that the breakpoint had locations (line 84 in the new version).  That's already tested in run_to_source_breakpoint.

**Review by dcci — APPROVED** [review]
lg, thanks

**Pull request merged**
