### PR TITLE
Fix CMake after merge

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@shahmishal swift-ci isn't responding... could you please force-merge this?

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
Thanks! Note that "test" won't do anything since this is only changing CMake files and the PR test is using xcodebuild.

**Pull request merged**
