### PR TITLE
Move initialization of data members into class declaration (NFC)

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Review by dcci — APPROVED** [review]
LGTM.

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
Looks like I forgot to commit half my patch...

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Pull request merged**
