### PR TITLE
[Swift] Add a test for getBitMaskForNoPayloadElements().

### PR DESCRIPTION
**Pull request by dcci**
The fix is in the swift compiler [pull request #25298]

<rdar://problem/51211938>

### CODE REVIEW

**Comment by dcci** [comment]
Please test with the following PR:
apple/swift#25298

@swift-ci Please test

**Comment by dcci** [comment]
Please test with the following PR:
apple/swift#25298

@swift-ci please test

**Comment by dcci** [comment]
@swift-ci please test macos platform

**Review by jckarter — APPROVED** [review]
Thanks @dcci!

**Comment by dcci** [comment]
Please test with the following PR:
apple/swift#25298

@swift-ci please test macos platform

**Pull request merged**
