### PR TITLE
 Swift: Support renamed types as Clang types.

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift/pull/22456
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@shahmishal swift-ci doesn't hear me...

**Comment by shahmishal** [comment]
Looking into the issue, I will let you know once it’s back online

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by shahmishal** [comment]
@adrian-prantl CI is still not back online.

**Comment by shahmishal** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
Yay, Thanks!

**Comment by shahmishal** [comment]
@swift-ci test and merge

**Pull request merged**
