### PR TITLE
Merge branch 'stable' into upstream-with-swift

### PR DESCRIPTION
**Pull request by bulbazord**

### CODE REVIEW

**Comment by bulbazord** [comment]
@swift-ci please test

**Review by adrian-prantl — COMMENTED** [review]
Thanks! Were there any controversial conflicts?

**Comment by bulbazord** [comment]
> Thanks! Were there any controversial conflicts?

Fortunately not, everything was very straightforward from looking at the individual changes. 

Unfortunately, it looks like clang on upstream-with-swift isn't building so this is difficult to verify.

**Comment by adrian-prantl** [comment]
Do you need me to force-merge it?

**Comment by bulbazord** [comment]
You could force merge if it you would like, but I was hoping to get some verification from swift-ci to make sure I didn't merge something incorrectly. We could force merge it and then clean up after the fact though, that would be fine too.

**Comment by bulbazord** [comment]
@swift-ci please test

**Comment by bulbazord** [comment]
@swift-ci please test

**Pull request merged**
