### PR TITLE
[SwiftASTContext] Remove the unneeded SwiftMangledNameVisitor.

### PR DESCRIPTION
**Pull request by dcci**
The reasons why this was needed escape me.
Part of the larger effort of making swift-lldb on a diet.

<rdar://problem/37710513>

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci please test

**Comment by jimingham** [comment]
This was used to go from mangled names to types before we started using swift::ide::getTypeFromMangledSymbol. With any luck we won't need to do that sort of work on our end anymore.

**Comment by dcci** [comment]
@jimingham I'm afraid this broke the xcodebuild. what should I do to remove this file from it?

**Comment by dcci** [comment]
@swift-ci please test

**Comment by dcci** [comment]
@swift-ci please test

**Pull request merged**
