### PR TITLE
[SwiftLanguageRuntime] Try to be more defensive.

### PR DESCRIPTION
**Pull request by dcci**
<rdar://problem/47348115>

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci test and merge

**Comment by fredriss** [comment]
Please put this on 5.0 too, it's obviously safe and can avoid a crash.

**Comment by jimingham** [comment]
Could you also change "M" to a variable name consistent with lldb conventions?  Local variables are of the form "foo_bar" with a lower case first letter and we discourage one letter variables.

**Comment by jasonmolenda** [comment]
Target::GetExecutableModule returns a ModuleSP so the convention is that this local is called module_sp.

**Pull request merged**
