### PR TITLE
Fix upstream-with-swift build

### PR DESCRIPTION
**Pull request by smeenai**
Adjust for LLVM changes

### CODE REVIEW

**Comment by smeenai** [comment]
CC @compnerd @xiaobai @dcci @JDevlieghere @adrian-prantl

**Review by JDevlieghere — APPROVED** [review]

**Comment by smeenai** [comment]
I'll need someone to test and merge this for me.

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Review by compnerd — APPROVED** [review]

**Comment by smeenai** [comment]
The error seems like a new issue. I'll see if I can fix that too.

**Comment by smeenai** [comment]
The CI failures seem like it's missing 04c5ceb18c6083a9a1b8b7ba474c1e608709a1f9 from Swift's master-next ... is it building against the right branch?

**Comment by smeenai** [comment]
https://github.com/apple/swift/pull/27450 should fix the build failure seen here, I think.

**Review by dcci — COMMENTED** [review]
LGTM

**Comment by adrian-prantl** [comment]
Thanks!

**Comment by smeenai** [comment]
Updated with some more fixes. I'd really appreciate a merge here. swift-lldb's upstream-with-swift merge is behind, and Swift master-next is broken as well (which should hopefully be fixed by https://github.com/apple/swift/pull/27462), so I'm not sure CI will be able to test this successfully, but I have tested it locally against an updated upstream-with-swift merge.

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift#27462

@swift-ci please test

**Comment by smeenai** [comment]
The build failures are caused by master-next being a mess and not by this PR. Can we please get this and https://github.com/apple/swift/pull/27462 in, so that we can at least fix part of the breakage? I don't think getting master-next CI completely healthy is reasonable for someone outside Apple to accomplish.

**Comment by smeenai** [comment]
Updated https://github.com/apple/swift/pull/27462. Can I get this tested again?

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift#27462

@swift-ci please test

**Comment by smeenai** [comment]
The build is failing because upstream-with-swift hasn't merged from llvm.org master for a while. It's fixing issues that'll be exposed by that merge though.

**Comment by smeenai** [comment]
Would appreciate another retest and merge here.

**Comment by bulbazord** [comment]
Please test with following PR:
apple/swift#27462

@swift-ci please test

**Comment by bulbazord** [comment]
Please test with following PR:
apple/swift#27462

@swift-ci please test

**Comment by gmittert** [comment]
Since the failures are unrelated to the changes here, merging since it's progress towards getting upstream-with-swift to build. If there are more failures, we can fix them in another PR.

**Pull request merged**
