### PR TITLE
[WIP/Dont merge Types] Initial plumbing for using remote mirrors in the debugger.

### PR DESCRIPTION
**Pull request by dcci**
<rdar://problem/36477650>

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci please test

**Comment by dcci** [comment]
@swift-ci please test

**Comment by dcci** [comment]
@swift-ci please test

**Comment by jimingham** [comment]
What expectations does ReadBytesResult have about the endianness of the data it reads back?  If it wants them in target byte order, then what you are doing is fine.  If it wants them in host byte order, then you probably want to use a DataExtractor.

**Comment by dcci** [comment]
Closing this, I'll reopen when we pick up this work again.

**Pull request closed without merging**
