### PR TITLE
Some more spring cleaning trying to get the bots green.

### PR DESCRIPTION
**Pull request by dcci**

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci test and merge

**Review by JDevlieghere — APPROVED** [review]

**Comment by dcci** [comment]
`TestLongLoops` passes unexpectedly on the bots but fails in PR testing.
@alexbbrown I'm at a loss here, can you please take a look?
(if you can't right away, I'll just skip this test, because it's too flakey to run in a PR setting).

**Comment by dcci** [comment]
@swift-ci please test macOS

**Comment by dcci** [comment]
@swift-ci test and merge

**Pull request closed without merging**
