### PR TITLE
[SwiftLanguageRuntime] Cope with the case where we have multiple symbols

### PR DESCRIPTION
**Pull request by dcci**

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci test and merge

**Review by JDevlieghere — APPROVED** [review]

**Comment by dcci** [comment]
@swift-ci please test linux

**Comment by dcci** [comment]
@JDevlieghere this test fails on and off on Linux:

```
22:03:38 --
22:03:38 Exit Code: 1
22:03:38 
22:03:38 Command Output (stderr):
22:03:38 --
22:03:38 error: process launch failed: 'A' packet returned an error: -1
22:03:38 /home/buildnode/jenkins/workspace/swift-lldb-PR-Linux/branch-swift-5.1-branch/lldb/lit/Reproducer/Functionalities/TestStepping.test:26:10: error: CHECK: expected string not found in input
22:03:38 # CHECK: Process {{.*}} stopped
22:03:38          ^
22:03:38 <stdin>:17:71: note: scanning from here
22:03:38 Breakpoint 4: where = TestStepping.test.tmp.out`c + 7 at stepping.c:23:25, address = 0x00000000004005e7
22:03:38                                                                       ^
22:03:38 <stdin>:17:76: note: possible intended match here
22:03:38 Breakpoint 4: where = TestStepping.test.tmp.out`c + 7 at stepping.c:23:25, address = 0x00000000004005e7
22:03:38                                                                            ^
22:03:38 
22:03:38 --
22:03:38 
22:03:38 ********************
22:03:38 Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 
22:04:26 Testing Time: 53.82s
22:04:26 ********************
22:04:26 Failing Tests (1):
22:04:26     LLDB :: Reproducer/Functionalities/TestStepping.test
```

**Comment by dcci** [comment]
@swift-ci test linux

**Pull request merged**
