### PR TITLE
Re-enable some tests that weren’t being run

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Review by dcci — CHANGES_REQUESTED** [review]
We have already a test for this.
`testcases/lang/swift/first_expr_module_load/`

But thanks, I forgot to close the SR (I just closed the rdar).

**Comment by slavapestov** [comment]
@dcci OK, the first patch still makes sense though.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by dcci** [comment]
sure, LG.

**Comment by dcci** [comment]
@slavapestov Presumably yesterday night I was too sleepy and I didn't notice this. "Re-enable some tests that weren’t being run", what lets you think they weren't being run?

**Comment by dcci** [comment]
Because, to the best of my knowledge, they're run when you build with the Cmake build. And I'm under the impression that `darwin` and `system-darwin`are actually synonyms in lit context, but don't quote me on that, I might be wrong.

**Pull request merged**
