### PR TITLE
Merge r284565 into master-next from upstream LLVM.org

### PR DESCRIPTION
**Pull request by tfiala**

### CODE REVIEW

**Comment by tfiala** [comment]
This change is known to have a small number of failing tests on macOS.  I'm putting it up to get an idea of how Linux is doing while I resolve the other issues.

@swift-ci Please test

**Comment by tfiala** [comment]
@swift-ci Please test Linux platform

**Comment by tfiala** [comment]
@swift-ci Please test Linux platform

**Comment by tfiala** [comment]
@swift-ci Please test Linux platform

**Comment by tfiala** [comment]
@shahmishal hmm, PR testing didn't kick off 3 times in a row.  Do we need to do something here?

**Comment by tfiala** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
This was due to github DNS issue.

**Comment by tfiala** [comment]
Gets us a step further on Linux (i.e. fix the CMake configuration failure, converting it now into a link-time failure).

@swift-ci Please test Linux platform

**Comment by tfiala** [comment]
@swift-ci Please test Linux platform

**Comment by tfiala** [comment]
@swift-ci Please test

(This change should get us clean builds, but tests are expected to still fail).

**Comment by tfiala** [comment]
@swift-ci Please test

**Comment by tfiala** [comment]
Status update:
* The Linux side now makes it through the build, but there are a number of failing tests.  Since the Swift has been updated from the master branch into master-next, I likely need to take the latest lldb master branch and bring it into master-next.  This may address some of the Swift failures.
* The macOS side is failing to build some of the unit tests (gtests).  I'll need to fix up the Xcode project file for that.  Unfortunately the Xcode file merge was a little too gnarly in the original import so I am fixing up the file by hand.

**Comment by tfiala** [comment]
Just fixed up the Xcode gtest portion of the build.

Expectations now are both macOS and Ubuntu build, but have test failures.

@swift-ci Please test

**Comment by tfiala** [comment]
> Expectations now are both macOS and Ubuntu build, but have test failures.

Take 2 on the Xcode project for build-script-driven macOS builds.

Also includes macOS test xfailing.  (Xfails will get bug-tracking numbers before merge).

@swift-ci Please test OS X platform

**Comment by tfiala** [comment]
@swift-ci Please test OS X platform

**Comment by tfiala** [comment]
Merged in latest from swift-lldb/master.  This was necessary to address some rev-locked fixes that go along with the recent swift/master => swift/master-next merge.

Expectations: macOS side nearly complete; Ubuntu side: need to see with swift-lldb/master merge, expecting to need to look into 10s of test failures. 

@swift-ci Please test

**Comment by tfiala** [comment]
@swift-ci Please test

**Comment by tfiala** [comment]
On macOS we are finally through the build and into the tests.  The test failures on CI that I'm not seeing locally are primarily due to the static Python swig bindings being out of date.  Fixing those up next.

**Comment by tfiala** [comment]
Updated the static Python swig bindings.

Note during the grand code reformatting exercise, we have started running the clang-format and autopep8 on the static swig bindings.  The commands to do that are:

```
clang-format -i scripts/Python/static-binding/LLDBWrapPython.cpp
autopep8 --in-place --aggressive --aggressive scripts/Python/static-binding/lldb.py
```

@swift-ci Please test

**Comment by tfiala** [comment]
@swift-ci Please test

**Comment by tfiala** [comment]
Based on the Linux tests, it looks like Linux took a regression in handling of some aspects of registers.  Most of the failing tests on Ubuntu are around register handling.

**Comment by tfiala** [comment]
macOS failure: TestModulesAutoImport.py is failing.  This is failing with a compiler error about the module having been touched and (it looks like) the module cache is stale.  That almost sounds like a CI configuration bot issue.  I'll investigate that.

On the Linux side, I have an Ubuntu 16.04 bot that has built cleanly and does not hit a single test failure listed in the CI bot.  I wonder if this is a compiler-specific issue.  I'll need to investigate that.

On the other hand, I am seeing an error in lldb-mi:
```
$ build/Ninja-DebugAssert/lldb-linux-x86_64/bin/lldb-mi
: CommandLine Error: Option 'debug' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

Looking at those now.

**Comment by tfiala** [comment]
The Ubuntu PR is using 14.04, FWIW.

**Comment by tfiala** [comment]
The issue I'm seeing with lldb-mi on my end is that CommandLine.cpp (from LLVM) claims 'debug' is registered more than once.  I think what's happening there is that lldb-mi is getting CommandLine.cpp from two sources: one from a shared object (maybe liblldb.so) and from static linking.  Those two are then fighting and re-registering default options (the --debug option).

The other potential issue that searching suggests might cause this behavior is a faulty compiler/linker.  I'm using clang-3.8.0-2ubuntu4 (tags/RELEASE_380/final), and the gold linker.

**Comment by tfiala** [comment]
News on the lldb-mi issue manifesting on Ubuntu: it is happening on SVN trunk as well as recently at r285393 (from this morning).  I confirmed this on Ubuntu 14.04 x86_64 with the following setup:

```
$ CC=clang-3.6 CXX=clang++-3.6 cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ../llvm -DLLDB_EXPORT_ALL_SYMBOLS=TRUE
$ ninja
```

The lldb-mi executable fails like so:
```
$ bin/lldb-mi
: CommandLine Error: Option 'debug' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

I filed the follow bug:
https://llvm.org/bugs/show_bug.cgi?id=30822

I am going to disable the lldb-mi tests on Ubuntu until that issue is resolved upstream.

**Comment by tfiala** [comment]
@swift-ci Please test

**Comment by tfiala** [comment]
@swift-ci Please test

**Comment by tfiala** [comment]
Removing lldb-mi not surprisingly eliminated the lldb-mi test failures, as those tests are skipped when lldb-mi is not present.

The Linux build still has several the register-related tests failing.  I am going to check if this is related to the use of the in-tree clang for building the test inferiors, which I haven't been using.  I'm going to try the test run locally with that compiler to see if I can repro it.

**Comment by tfiala** [comment]
I've got a fix for the issue that was hitting lldb-mi in debug scenarios in review here:
https://reviews.llvm.org/D26093

**Comment by tfiala** [comment]
I have put in the preliminary fix for the lldb-mi issue and reverted out the exclusion of lldb-mi.  (i.e. we are back to building lldb-mi on CMake-based builds).

To address the rest of the Linux test issues, I'm building an in-tree clang with compiler-rt, and I'll use that as the compiler that builds the LLDB test suite test inferiors.  I'm hoping that will allow me to reproduce the issues that the Ubuntu CI are hitting.  (Currently I am hitting 0 issues on Ubuntu 16.04 x86_64 using the clang 3.8 compiler for test inferiors.)

**Comment by tfiala** [comment]
I think the Register issue on Ubuntu 14.04 (which technically we should be off now) may be the clang-3.6 issue that @shahmishal saw in the past.  If so, the work-around there was to upgrade to clang-3.8.  I have not been able to reproduce this on Ubuntu 16.04 with clang-3.8.

These are the results I'm getting:
```
lldb/test/dotest.py --swift-compiler `pwd`/build/Ninja-DebugAssert/swift-linux-x86_64/bin/swiftc --executable `pwd`/build/Ninja-DebugAssert/lldb-linux-x86_64/bin/lldb -C `pwd`/build/Ninja-DebugAssert/llvm-linux-x86_64/bin/clang --rerun-all-issues
Testing: 708 test suites, 6 threads
708 out of 708 test suites processed - TestGdbRemote_qThreadStopInfo.py
=============
Issue Details
=============
UNEXPECTED SUCCESS: testREPL (repl/pounwrapping/TestPOUnwrapping.py)
UNEXPECTED SUCCESS: testREPL (repl/structs/TestREPLStructs.py)
UNEXPECTED SUCCESS: test_Hc_then_Csignal_signals_correct_thread_launch_llgs (tools/lldb-server/TestLldbGdbServer.py)
UNEXPECTED SUCCESS: test_and_python_api_dwarf (lang/c/bitfields/TestBitfields.py)
UNEXPECTED SUCCESS: test_and_python_api_dwo (lang/c/bitfields/TestBitfields.py)
UNEXPECTED SUCCESS: test_and_python_api_gmodules (lang/c/bitfields/TestBitfields.py)
UNEXPECTED SUCCESS: test_any_type_dwarf (lang/swift/any/TestSwiftAnyType.py)
UNEXPECTED SUCCESS: test_any_type_dwo (lang/swift/any/TestSwiftAnyType.py)
UNEXPECTED SUCCESS: test_any_type_gmodules (lang/swift/any/TestSwiftAnyType.py)
UNEXPECTED SUCCESS: test_dwarf (functionalities/thread/thread_exit/TestThreadExit.py)
UNEXPECTED SUCCESS: test_dwarf (functionalities/tsan/thread_leak/TestTsanThreadLeak.py)
UNEXPECTED SUCCESS: test_dwarf (functionalities/thread/exit_during_break/TestExitDuringBreak.py)
UNEXPECTED SUCCESS: test_dwarf (functionalities/asan/TestReportData.py)
UNEXPECTED SUCCESS: test_dwarf (functionalities/asan/TestMemoryHistory.py)
UNEXPECTED SUCCESS: test_dwarf (lang/swift/file_private/TestFilePrivate.py)
UNEXPECTED SUCCESS: test_dwo (lang/swift/file_private/TestFilePrivate.py)
UNEXPECTED SUCCESS: test_dwo (functionalities/asan/TestReportData.py)
UNEXPECTED SUCCESS: test_dwo (functionalities/asan/TestMemoryHistory.py)
UNEXPECTED SUCCESS: test_dwo (functionalities/tsan/thread_leak/TestTsanThreadLeak.py)
UNEXPECTED SUCCESS: test_dwo (functionalities/thread/thread_exit/TestThreadExit.py)
UNEXPECTED SUCCESS: test_dwo (functionalities/thread/exit_during_break/TestExitDuringBreak.py)
UNEXPECTED SUCCESS: test_get_value_as_unsigned_sbapi_dwarf (lang/swift/get_value/TestSwiftGetValueAsUnsigned.py)
UNEXPECTED SUCCESS: test_get_value_as_unsigned_sbapi_dwo (lang/swift/get_value/TestSwiftGetValueAsUnsigned.py)
UNEXPECTED SUCCESS: test_get_value_as_unsigned_sbapi_gmodules (lang/swift/get_value/TestSwiftGetValueAsUnsigned.py)
UNEXPECTED SUCCESS: test_gmodules (lang/swift/file_private/TestFilePrivate.py)
UNEXPECTED SUCCESS: test_gmodules (functionalities/asan/TestMemoryHistory.py)
UNEXPECTED SUCCESS: test_gmodules (functionalities/tsan/thread_leak/TestTsanThreadLeak.py)
UNEXPECTED SUCCESS: test_gmodules (functionalities/thread/exit_during_break/TestExitDuringBreak.py)
UNEXPECTED SUCCESS: test_gmodules (functionalities/thread/thread_exit/TestThreadExit.py)
UNEXPECTED SUCCESS: test_gmodules (functionalities/asan/TestReportData.py)
UNEXPECTED SUCCESS: test_lldbmi_break_insert_function (tools/lldb-mi/breakpoint/TestMiBreak.py)
UNEXPECTED SUCCESS: test_lldbmi_break_insert_function_pending (tools/lldb-mi/breakpoint/TestMiBreak.py)
UNEXPECTED SUCCESS: test_lldbmi_gdb_set_target_async_off (tools/lldb-mi/TestMiGdbSetShow.py)
UNEXPECTED SUCCESS: test_lldbmi_process_output (tools/lldb-mi/syntax/TestMiSyntax.py)
UNEXPECTED SUCCESS: test_lldbmi_settings_set_target_run_args_after (tools/lldb-mi/interpreter/TestMiInterpreterExec.py)
UNEXPECTED SUCCESS: test_restart_bug_gmodules (functionalities/signal/raise/TestRaise.py)
UNEXPECTED SUCCESS: test_watched_var_should_only_hit_when_in_scope_dwarf (functionalities/watchpoint/variable_out_of_scope/TestWatchedVarHitWhenInScope.py)
UNEXPECTED SUCCESS: test_watched_var_should_only_hit_when_in_scope_dwo (functionalities/watchpoint/variable_out_of_scope/TestWatchedVarHitWhenInScope.py)
UNEXPECTED SUCCESS: test_watched_var_should_only_hit_when_in_scope_gmodules (functionalities/watchpoint/variable_out_of_scope/TestWatchedVarHitWhenInScope.py)
UNEXPECTED SUCCESS: test_with_dwarf (lang/cpp/printf/TestPrintf.py)
UNEXPECTED SUCCESS: test_with_dwarf (lang/swift/associated_self_type/TestSwiftAssociatedSelfType.py)
UNEXPECTED SUCCESS: test_with_dwarf (lang/swift/partially_generic_func/enum/TestSwiftPartiallyGenericFuncEnum.py)
UNEXPECTED SUCCESS: test_with_dwarf (lang/swift/generic_arg_in_extension/TestSwiftGenericArgInExtension.py)
UNEXPECTED SUCCESS: test_with_dwo (lang/swift/partially_generic_func/enum/TestSwiftPartiallyGenericFuncEnum.py)
UNEXPECTED SUCCESS: test_with_dwo (lang/cpp/printf/TestPrintf.py)
UNEXPECTED SUCCESS: test_with_dwo (lang/swift/associated_self_type/TestSwiftAssociatedSelfType.py)
UNEXPECTED SUCCESS: test_with_dwo (lang/swift/generic_arg_in_extension/TestSwiftGenericArgInExtension.py)
UNEXPECTED SUCCESS: test_with_gmodules (lang/swift/generic_arg_in_extension/TestSwiftGenericArgInExtension.py)
UNEXPECTED SUCCESS: test_with_gmodules (lang/cpp/printf/TestPrintf.py)
UNEXPECTED SUCCESS: test_with_gmodules (lang/swift/associated_self_type/TestSwiftAssociatedSelfType.py)
UNEXPECTED SUCCESS: test_with_gmodules (lang/swift/partially_generic_func/enum/TestSwiftPartiallyGenericFuncEnum.py)

===================
Test Result Summary
===================
Test Methods:       2958
Reruns:                0
Success:            1833
Expected Failure:    168
Failure:               0
Error:                 0
Exceptional Exit:      0
Unexpected Success:   51
Skip:                906
Timeout:               0
Expected Timeout:      0
➜  lldb-github-next
```

I'm going to put this in now to get it moving and see if the other versions of Ubuntu see this issue.

**Comment by tfiala** [comment]
Note a new merge in swift/master-next, swift-llvm/stable-next and swift-clang/stable-next just landed.  This change here was done against the following commits, which were valid tips as of yesterday:

* swift-llvm/stable-next:
```
commit 957412bff560af3485ed1f530e06fca2a218ee4f
Merge: 987debf 50de6f6
Author: Bob Wilson <bob.wilson@apple.com>
Date:   Mon Oct 17 11:49:40 2016 -0700

    Merge commit '50de6f631b9eaa8fa3a9d41763a2151749eb36d3' into stable-next
```

* swift-clang/stable-next:
```
commit a8d2fd8e7eb5f77125660104cac84f93f90740cd
Author: Erik Pilkington <erik.pilkington@gmail.com>
Date:   Tue Oct 18 15:26:43 2016 +0000

    Revert r284265 "[Sema] Refactor context checking for availability diagnostics"

    This has a bug in it, pointed out by Bob Wilson!

    git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@284486 91177308-0d34-0410-b5e6-96231b3b80d8
```

* swift/maser-next:
```
commit 99721e6514be585ddf8d6a1967fe3ba93ef740aa
Merge: 1caba3e 7213a4d
Author: Todd Fiala <todd.fiala@gmail.com>
Date:   Wed Oct 19 11:18:16 2016 -0700

    Merge pull request #5355 from tfiala/fixup-header-symlink

    fixup header symlink issue due to clang 3.8 assumption
```

* swift-cmark/master:
```
commit 5af77f3c1d7f34f252a897094936ac4d162adf4b
Merge: 6873b63 df5236d
Author: John MacFarlane <jgm@berkeley.edu>
Date:   Thu Dec 10 13:37:05 2015 -0800

    Merge pull request #95 from kainjow/master

    Fix warnings about dropping const qualifier
```

I'll need to get another merge going here shortly to catch up with swift/master-next.

**Pull request merged**
