### PR TITLE
Add a test for resolving overloaded == operators with different visibilities.

### PR DESCRIPTION
**Pull request by jrose-apple**
LLDB-side tests for apple/swift#4556, written by @jimingham. Cannot be tested until that PR is merged.

rdar://problem/27015195

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test Linux platform

**Comment by jrose-apple** [comment]
No PR testing for LLDB+Linux+swift-3.0-branch? cc @shahmishal

**Comment by shahmishal** [comment]
@jrose-apple soon :)

**Comment by shahmishal** [comment]
@swift-ci Please test Linux

**Comment by shahmishal** [comment]
@jrose-apple Fixed

**Comment by tfiala** [comment]
This should have already gone in.  Running one more test to make sure that's still the case.

@swift-ci Please test

**Pull request merged**
