### PR TITLE
Cherry pick changes to the 5.1 branch

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
great!

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by slavapestov** [comment]
@adrian-prantl I haven't tested this locally yet. It might not even compile. I'm on it, don't worry.

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
Should be fixed now

**Comment by slavapestov** [comment]
Ok, I need to cherry-pick some RemoteAST fixes to swift-5.1-branch on the Swift side too.

**Comment by slavapestov** [comment]
https://github.com/apple/swift/pull/23285
@swift-ci Please test Linux

**Pull request merged**
