### PR TITLE
Adjust for SVN r346165

### PR DESCRIPTION
**Pull request by compnerd**

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @dcci @adrian-prantl 

@adrian-prantl - I'm not sure if there is an execution context here that needs to be plumbed through.

**Comment by adrian-prantl** [comment]
Thanks for doing the work, but can we abandon this in favor of https://github.com/apple/swift-lldb/pull/1032 ? That PR does thread through the exe_ctx.

**Comment by adrian-prantl** [comment]
The automerger should bubble it up to upstream-with-swift eventually.

**Review by adrian-prantl — CHANGES_REQUESTED** [review]
https://github.com/apple/swift-lldb/pull/1032 does this, too.

**Comment by compnerd** [comment]
Sure, I'm fine with #1032 instead.

**Pull request closed without merging**
