### PR TITLE
[SwiftLanguageRuntime] Fix the error return register on AArch64.

### PR DESCRIPTION
**Pull request by dcci**
No test as this fixes TestExpressionErrorBreakpoint there.

### CODE REVIEW

**Comment by dcci** [comment]
I didn't run the test suite myself, just tried a similar test program to the one in the test. Close enough I guess.

**Comment by dcci** [comment]
@swift-ci test and merge

**Comment by dcci** [comment]
For future reference (mainly for myself), the values are documented in LLVM (e.g.

```
 $ grep  SwiftError lib/Target/AArch64/AArch64CallingConvention.td
```

thanks to @aschwaighofer for pointing out)

**Comment by jrose-apple** [comment]
Is there any way to get these values from the various target definitions, rather than copying them here?

**Comment by dcci** [comment]
@jrose-apple yes, there should be one (this hardcoding makes me uneasy too). 
How does swiftc access them?

**Comment by jrose-apple** [comment]
swiftc just lets LLVM figure it out; it doesn't hardcode anything. I think you'll have to ask LLVM for the target's calling convention info yourself, something that's out of my area of expertise.

**Comment by dcci** [comment]
@aschwaighofer / @mikeash / @jckarter any ideas on how we make this more robust in face of changes? I do understand that having ABI-stable binaries make this less important, but still I think this information should be entirely opaque to lldb.

**Comment by mikeash** [comment]
In theory, I like the idea of consolidating the information. In practice, I think it's reasonable for some duplicated information like this to exist in the debugger.

Would it be possible to have lldb consume the information from the .td file? This document implies it should be possible to make an arbitrary backend for the .td parser, and maybe lldb could have one that emits the information it needs. https://llvm.org/docs/TableGen/index.html

**Pull request merged**
