### PR TITLE
Merge 5.1

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@shahmishal It looks like swift-ci can't hear me...

**Comment by shahmishal** [comment]
Can you try again? we had network outage

**Comment by adrian-prantl** [comment]
Seems to work now, thanks!

**Pull request merged**
