### PR TITLE
Formatting support for UTF-8 String

### PR DESCRIPTION
**Pull request by milseman**
This adds formatting support for the UTF-8 String.

### CODE REVIEW

**Comment by dcci** [comment]
Looking at the failures now, @milseman, stay tuned.

**Comment by dcci** [comment]
Sent you a pull request with the fix here:
https://github.com/milseman/swift-lldb/pull/1

**Comment by milseman** [comment]
@swift-ci please smoke test and merge

**Comment by shahmishal** [comment]
Merged to unblock CI

**Pull request merged**
