### PR TITLE
Rename various ObjC-visible classes

### PR DESCRIPTION
**Pull request by mikeash**
Swift is renaming some classes that are visible to Objective-C to avoid conflicts between older versions and ABI-stable versions. Change those names here as well.

This goes with this Swift PR: apple/swift#19295

rdar://problem/35768222

### CODE REVIEW

**Review by dcci — APPROVED** [review]
We discussed this already via e-mail, but, just in case, explicitly approving here.

**Comment by mikeash** [comment]
https://github.com/apple/swift/pull/19295

@swift-ci please test

**Comment by mikeash** [comment]
apple/swift#19295

@swift-ci please test

**Comment by mikeash** [comment]
apple/swift#19295

@swift-ci please test

**Pull request merged**
