### PR TITLE
 Enable previously XFAILed test.

### PR DESCRIPTION
**Pull request by adrian-prantl**
It looks like this was accidentally left XFAILed even though the
underlying bug had been resolved.

<rdar://problem/49526725>

### CODE REVIEW

**Comment by adrian-prantl** [comment]
Do the typename changes look right, or is there still a bug?

**Comment by adrian-prantl** [comment]
Here's the source:

```
public struct MyStruct {
    fileprivate typealias IntegerType = Int
    private var m_integer = IntegerType(345)
    fileprivate func Foo(_ i : IntegerType)
    {
        print("i = \(i)") // breakpoint 1
    }
    
    fileprivate func Bar()
    {
        let a : Dictionary<String, IntegerType> = [ "hello" : 234 ]
        print("a = \(a)") // breakpoint 2
    }
    
}

func main() {
    let s = MyStruct()
    s.Foo(123)
    s.Bar()
}

main()
```

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by jrose-apple** [comment]
Yes, the intervening ".Type" was always wrong. Thanks, Adrian!

**Pull request merged**
