### PR TITLE
Abstract common functionality from GetBitSize and GetByteStride.

### PR DESCRIPTION
**Pull request by adrian-prantl**
Here's my attempt at factoring out the common pattern in these functions. Let me know what you think!

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by dcci** [comment]
I thought about using lambdas + function_ref<> but... is this the right tradeoff?
Is it true that this shares more code, but it also adds more code, and it's much harder to read than before.

**Comment by adrian-prantl** [comment]
frankly, I'm not sure either. Are there more functions that share this pattern?

**Comment by dcci** [comment]
Not I'm aware of.

**Pull request closed without merging**
