### PR TITLE
[DataFormatter] Teach lldb about unmanaged strings

### PR DESCRIPTION
**Pull request by vedantk**
This gets us part of the way towards understanding the new string ABI.

(Related to rdar://36744510)

### CODE REVIEW

**Comment by vedantk** [comment]
@swift-ci test

**Comment by vedantk** [comment]
@dcci I'll eventually un-xfail tests to get test coverage for this change.

**Comment by vedantk** [comment]
@swift-ci test and merge

**Comment by vedantk** [comment]
@swift-ci test

**Comment by vedantk** [comment]
@swift-ci Please test

**Comment by vedantk** [comment]
@swift-ci Please test macOS platform

**Comment by vedantk** [comment]
@swift-ci Test macOS platform

**Comment by vedantk** [comment]
@swift-ci Test OS X platform

**Comment by vedantk** [comment]
@swift-ci test OS X platform

**Comment by vedantk** [comment]
@swift-ci test OS X platform

**Comment by vedantk** [comment]
The compiles on the Linux bot were killed, somehow.

**Comment by vedantk** [comment]
@swift-ci test

**Comment by vedantk** [comment]
@swift-ci Please test

**Comment by vedantk** [comment]
@shahmishal I've batched a few test infrastructure fixes along with this PR, all of which @dcci has reviewed. Could you override-merge this as well to help the bots out?

**Comment by shahmishal** [comment]
Merged to unblock CI.

**Comment by vedantk** [comment]
@shahmishal Thanks so much!

**Pull request merged**
