### PR TITLE
CMake build and test support for Darwin

### PR DESCRIPTION
**Pull request by llvm-beanz**
This sequence of patches is a combination of a bunch of cherry-picks from LLVM.org to support building and running the test suite on Darwin using CMake, and some additional patches to get the Swift support also working with CMake on Darwin.

### CODE REVIEW

**Comment by llvm-beanz** [comment]
@swift-ci Please smoke test.

**Comment by llvm-beanz** [comment]
I should note, with this patch there are 6 failing tests and 6 tests with errors. The 6 failing tests also fail on LLVM.org with CMake builds (so no regression). The tests with errors are:

`FAIL: test_dsym (functionalities/exec/TestExec.py)
FAIL: test_dwarf (functionalities/exec/TestExec.py)
FAIL: test_expr_dsym (lang/c/modules/TestCModules.py)
FAIL: test_expr_dwarf (lang/c/modules/TestCModules.py)
FAIL: test_expr_gmodules (lang/c/modules/TestCModules.py)
FAIL: test_gmodules (functionalities/exec/TestExec.py)
ERROR: testREPL (repl/lazy_reverse/TestLazyReverse.py)
ERROR: testREPL (repl/pounwrapping/TestPOUnwrapping.py)
ERROR: testREPL (repl/classes/TestREPLClasses.py)
ERROR: testREPL (repl/type_lookup/TestREPLTypeLookup.py)
ERROR: testREPL (repl/recursive_class/TestREPLRecursiveClass.py)
ERROR: testREPL (repl/structs/TestREPLStructs.py)
ERROR: [EXCEPTIONAL EXIT 11 (SIGSEGV)] test_swift_no_target_dsym (lang/swift/expression/no_calculator/TestSwiftNoProcess.py)`

**Comment by tfiala** [comment]
@swift-ci Please test

**Comment by tfiala** [comment]
@swift-ci Please test

**Comment by tfiala** [comment]
The macOS PR test failure is now also failing in master.  This is unrelated to Chris' change here.

**Pull request merged**
