### PR TITLE
SR-2100 - Add support for multi-lib systems

### PR DESCRIPTION
**Pull request by ghost**
[SR-2100 - Add support for multi-lib systems](https://bugs.swift.org/browse/SR-2100)

Use the LLVM_LIBDIR_SUFFIX [provided by LLVM](https://llvm.org/docs/CMake.html) project itself to control the creation of a suffix
for /lib dir under Linux system, so systems that uses lib64 folder insted of lib folder for 64-bit 
libraries can use Swift without patches.

### CODE REVIEW

**Comment by dcci** [comment]
@capent this looks alright [sorry, I missed this one when you first posted]. @vedantk, what do you think?

**Comment by dcci** [comment]
@capent can you squash all the commits into one? After that, I'll run the tests and merge

**Review by vedantk — APPROVED** [review]

**Comment by dcci** [comment]
@capent hello, can you please rebase this so I can merge it?

**Comment by ghost** [comment]
@dcci Sure! I will do it now.

**Comment by dcci** [comment]
@capent I'm afraid the branch is not in a mergeable state because there are conflicts (in `tools/repl/swift/CMakeLists.txt`)

What I do to fix is: 
```
git rebase -i master
git push -f <branch
```

Please let me know if you still have trouble. Thanks again for your contribution.

**Comment by ghost** [comment]
@dcci Well... i managed to rebase it to just two commits, is this good enough?

**Comment by dcci** [comment]
There's something weird in your commits:
```
SR-2100 - Adapting llbuild for multilib - general framework
```

Maybe open a new pull request on a new branch with this change?

**Comment by ghost** [comment]
@dcci You are right, now that i took notice that back in 2017 i made one commit with the wrong message. The problem that i have is: this change is old, and it has more than 700 intermediate commits between changes. Git is failing to rewind the history to squash it cleanly, and cherry picking the only four commits that i need (828b3f4, 6ef3ee3, 8487f43, 6ca677d) onto the 8b93add is not working neither.

I still have the original repository here, because i don't dare to do a rebase without backups. I can restore, and try again. If this last attempt fail i will do a new pull request. I don't want to pollute you guys with needless pull requests.

**Comment by dcci** [comment]
@capent asi this is a single line change, I recommend to close this, and apply the change on a new clean branch.

**Comment by ghost** [comment]
@dcci Ok! Closing it. In a few minutes i will reapply the pull request from a clean branch.

**Pull request closed without merging**
