### PR TITLE
Cherry pick asserts sink

### PR DESCRIPTION
**Pull request by bulbazord**
cc @dcci @JDevlieghere @compnerd

### CODE REVIEW

**Comment by dcci** [comment]
LGTM

**Review by dcci — APPROVED** [review]

**Comment by dcci** [comment]
@swift-ci test and merge

**Comment by bulbazord** [comment]
Hmm, the tests are failing because of a missing include. It looks like that include is added in a commit in #1638, so this should go in after that one.

**Comment by compnerd** [comment]
@swift-ci please test

**Pull request merged**
