### PR TITLE
Cleanup unexpected success for Objective-C

### PR DESCRIPTION
**Pull request by JDevlieghere**
I'm going through the unexpected successes in the test suite. I'm re-enalbing the ones for which the radar suggests they might/are fixed on the condition that they works on all of my machines. Probably some of them will still fail on the bots, which we'll hopefully find out here.

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by dcci** [comment]
This is a cherry pick of my previous commit, right?
If so, go ahead.

**Comment by JDevlieghere** [comment]
Yup + one more test that was already re-enabled upstream. I'm not expecting any issues here.

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Pull request merged**
