### PR TITLE
Grab bag of cleanups for lldb

### PR DESCRIPTION
**Pull request by dcci**
(mainly add and re-enable tests)

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci test and merge

**Comment by dcci** [comment]
@swift-ci test and merge

**Comment by dcci** [comment]
@swift-ci test linux platform

**Comment by dcci** [comment]
@swift-ci test linux platform

**Comment by shahmishal** [comment]
@swift-ci test linux platform

**Pull request merged**
