### PR TITLE
Adjust for change to AbstractStorageDecl storage representation.

### PR DESCRIPTION
**Pull request by rjmccall**
I'm not really sure what this code was trying to do, but this maintains
exactly the current behavior.

### CODE REVIEW

**Review by dcci — APPROVED** [review]
I'm not entirely sure why lldb has to fix the captures manually, I'll take a look separately. But given this is basically no behavior change, lgtm.

**Comment by rjmccall** [comment]
@swift-ci Please test.

**Comment by rjmccall** [comment]
This was tested together with https://github.com/apple/swift/pull/17566 but I forgot to trigger testing on this side before clicking "Merge" there; if someone with admin powers wants to force-merge it, that would be great.

**Comment by rjmccall** [comment]
(To be clear, the test failures here seem to be the same as the existing Linux test failures.)

**Comment by dcci** [comment]
Looking at the lldb failures now.

**Pull request merged**
