### PR TITLE
Remove TestMultilineExpressions.py in favour of upstream lit test

### PR DESCRIPTION
**Pull request by weliveindetail**
Remove python test TestMultilineExpressions.py in favour of upstream lit test: https://reviews.llvm.org/D52270

### CODE REVIEW

**Comment by weliveindetail** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
This test is swift-lldb-only?

**Review by adrian-prantl — APPROVED** [review]

**Comment by dcci** [comment]
If you're removing this test, can you please add the other one?

**Review by adrian-prantl — CHANGES_REQUESTED** [review]
Please let me know if I'm just totally confused, but that file also exists in llvm.org. We should remove it there (and cherry-pick) and not here only.

**Comment by weliveindetail** [comment]
Sorry, the original issue was reported for swift-lldb. I didn't see this exists upstream. Removed the file(s) in https://reviews.llvm.org/D52270 and closing this.

**Pull request closed without merging**
