### PR TITLE
[Swift] Remove uses of deprecated FunctionType::getInput()

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Review by dcci — APPROVED** [review]
This makes sense to me.
There are some build failures, but they should be straightforward.

**Comment by slavapestov** [comment]
@dcci Sorry about that. I forgot to wrap the result in a CompilerType (and then ran the wrong build-script command so it didn't actually rebuild lldb :-) )

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by dcci** [comment]
No worries, we have type checking for that :)

**Comment by slavapestov** [comment]
Hmm.

```
15:28:22 fatal: unable to access 'https://github.com/apple/swift-llbuild.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
```

**Comment by slavapestov** [comment]
@swift-ci Please test macOS

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Pull request merged**
