### PR TITLE
 Convert homebrew unordered maps to llvm::DenseMap.  …

### PR DESCRIPTION
**Pull request by adrian-prantl**
NFC

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by JDevlieghere** [comment]
@swift-ci test and merge

**Comment by JDevlieghere** [comment]
@swift-ci test and merge

**Comment by dcci** [comment]
```
18:23:41 
/home/buildnode/jenkins/workspace/swift-lldb-PR-Linux/branch-stable/lldb/source/Target/SwiftLanguageRuntime.cpp:1637:30: error: no matching member function for call to 'find'
18:23:41   auto it = m_member_offsets.find(key);
18:23:41             ~~~~~~~~~~~~~~~~~^~~~
```

I do believe this fails because of differences between `libc++` and `libstdcxx`. It's not extremely urgent, so I'll let Adrian handle it when he's back.

**Comment by dcci** [comment]
```
18:23:41 
/home/buildnode/jenkins/workspace/swift-lldb-PR-Linux/branch-stable/lldb/source/Target/SwiftLanguageRuntime.cpp:1637:30: error: no matching member function for call to 'find'
18:23:41   auto it = m_member_offsets.find(key);
18:23:41             ~~~~~~~~~~~~~~~~~^~~~
```

I do believe this fails because of differences between `libc++` and `libstdcxx`. It's not extremely urgent, so I'll let Adrian handle it when he's back.

**Review by dcci — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Pull request merged**
