### PR TITLE
Manually merged the contents on master-next into master.

### PR DESCRIPTION
**Pull request by clayborg**
Over a year of merges has left master in an older state where many LLVM and Clang changes in LLDB were not in this branch. This merge tries to rectify this by merging master-next (which was update to date with SVN top of tree) into master manually as the git merge happily left old code, had test cases missing, and many other issues.

### CODE REVIEW

**Comment by clayborg** [comment]
@swift-ci please test

**Comment by clayborg** [comment]
Removed source/Core/CxaDemangle.cpp.

@swift-ci please test

**Comment by clayborg** [comment]
@swift-ci please test

**Comment by clayborg** [comment]
@swift-ci please test

**Comment by clayborg** [comment]
@swift-ci please test

**Comment by dcci** [comment]
I'm pretty sure this is really irrelevant right now. Closing.

**Pull request closed without merging**
