### PR TITLE
[Swift] Add a test for the target.swift-framework-search-paths setting

### PR DESCRIPTION
**Pull request by Jnosh**
This is basically the same test as for target.swift-module-search-paths but using a framework instead of a module.

### CODE REVIEW

**Comment by tfiala** [comment]
@swift-ci Please test

**Comment by tfiala** [comment]
@swift-ci Please test OS X platform

**Comment by dcci** [comment]
@Jnosh it's been a while since you submitted this pull request. If you're still interested, do you mind to rebase & test so that I can take a look and consider this for a merge? Thanks for your patience!

**Comment by Jnosh** [comment]
@dcci Sure, I’ll take a look at it over the weekend.

**Comment by dcci** [comment]
@Jnosh any progress on this?

**Comment by dcci** [comment]
@Jnosh did you get a chance to take a look at this?

**Comment by dcci** [comment]
@Jnosh what's the status of this?

**Comment by dcci** [comment]
This doesn't apply anymore, and there was no activity on this for a while.
Thanks for this, feel free to reopen in case you want to go down this road.

**Pull request closed without merging**
