### PR TITLE
[5.1] Replace opaque types with their runtime underlying type.

### PR DESCRIPTION
**Pull request by jckarter**
rdar://problem/46138166

### CODE REVIEW

**Comment by jckarter** [comment]
Please test with the following pull request:
https://github.com/apple/swift/pull/24446

@swift-ci Please test

**Review by dcci — APPROVED** [review]

**Comment by jckarter** [comment]
@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test OS X

**Comment by davezarzycki** [comment]
@jckarter – This broke my Red Hat Linux Fedora 30 box. Was this intentional?

```
FAILED: tools/lldb/source/Target/CMakeFiles/lldbTarget.dir/SwiftLanguageRuntime.cpp.o 
/p/llvm/bin/clang++  -DGTEST_HAS_RTTI=0 -DHAVE_ROUND -DLIBXML2_DEFINED -DLLDB_CONFIGURATION_RELEASE -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/lldb/source/Target -I/home/dave/s/u/lldb/source/Target -Itools/lldb/include -I/home/dave/s/u/lldb/include -I/usr/include/libxml2 -Iinclude -I/home/dave/s/u/llvm/include -I/usr/include/python2.7 -I/home/dave/s/u/llvm/../clang/include -Itools/lldb/../clang/include -I/home/dave/s/u/llvm/../swift/include -Itools/lldb/../swift/include -I/home/dave/s/u/lldb/source/. -I/home/dave/s/u/lldb/source/Target/../Plugins/Process/Utility -Wno-c11-extensions -Wno-gnu-anonymous-struct -Wno-unused-local-typedef -Wno-dollar-in-identifier-extension -Wno-unused-private-field -Wno-gnu-statement-expression -Wno-c99-extensions -Wno-nullability-extension -Wno-format-pedantic -Wno-global-constructors -Wno-four-char-constants -Wno-c++17-extensions -Wno-global-constructors -Werror=macro-redefined -Wno-defaulted-function-deleted -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-deprecated-register -Wno-vla-extension -O2    -UNDEBUG  -march=native -mno-avx512f -fno-omit-frame-pointer -fno-vectorize -fno-slp-vectorize -mno-omit-leaf-frame-pointer -fno-exceptions -fno-rtti -Wno-dollar-in-identifier-extension -MD -MT tools/lldb/source/Target/CMakeFiles/lldbTarget.dir/SwiftLanguageRuntime.cpp.o -MF tools/lldb/source/Target/CMakeFiles/lldbTarget.dir/SwiftLanguageRuntime.cpp.o.d -o tools/lldb/source/Target/CMakeFiles/lldbTarget.dir/SwiftLanguageRuntime.cpp.o -c /home/dave/s/u/lldb/source/Target/SwiftLanguageRuntime.cpp
/home/dave/s/u/lldb/source/Target/SwiftLanguageRuntime.cpp:1283:12: warning: unused variable 'other_sym' [-Wunused-variable]
      auto other_sym = sc_list.GetContextAtIndex(i, sym_ctx);
           ^
/home/dave/s/u/lldb/source/Target/SwiftLanguageRuntime.cpp:1284:12: warning: unused variable 'other_load_addr' [-Wunused-variable]
      auto other_load_addr =
           ^
/home/dave/s/u/lldb/source/Target/SwiftLanguageRuntime.cpp:1278:10: warning: unused variable 'sym' [-Wunused-variable]
    auto sym = sc_list.GetContextAtIndex(0, sym_ctx);
         ^
/home/dave/s/u/lldb/source/Target/SwiftLanguageRuntime.cpp:1943:48: warning: format specifies type 'unsigned long long' but the argument has type 'lldb::addr_t' (aka 'unsigned long') [-Wformat]
    log->Printf("existential address is %llu", existential_address);
                                        ~~~~   ^~~~~~~~~~~~~~~~~~~
                                        %lu
/home/dave/s/u/lldb/source/Target/SwiftLanguageRuntime.cpp:2041:29: error: no member named 'mangleOpaqueTypeDescriptor' in 'swift::Mangle::ASTMangler'
                    mangler.mangleOpaqueTypeDescriptor(opaque_type->getDecl()));
                    ~~~~~~~ ^
/home/dave/s/u/lldb/source/Target/SwiftLanguageRuntime.cpp:2069:24: error: no member named 'getUnderlyingTypeForOpaqueType' in 'swift::remoteAST::RemoteASTContext'
            remote_ast.getUnderlyingTypeForOpaqueType(
            ~~~~~~~~~~ ^
/home/dave/s/u/lldb/source/Target/SwiftLanguageRuntime.cpp:2072:58: error: no member named 'getOrdinal' in 'swift::OpaqueTypeArchetypeType'
                                            opaque_type->getOrdinal());
                                            ~~~~~~~~~~~  ^
/home/dave/s/u/lldb/source/Target/SwiftLanguageRuntime.cpp:2553:18: warning: unused variable 'swift_can_type' [-Wunused-variable]
  swift::CanType swift_can_type(GetCanonicalSwiftType(type));
                 ^
5 warnings and 3 errors generated.

```

**Comment by compnerd** [comment]
This broke the Windows CI!  https://dev.azure.com/compnerd/windows-swift/_build/results?buildId=1979

**Comment by compnerd** [comment]
Apparently, this also broke the Linux, macOS CI: https://ci.swift.org/job/swift-PR-Linux/13092/consoleFull#1389190643122a513-f36a-4c87-8ed7-cbc36a1ec144

```
02:05:19 
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/source/Target/SwiftLanguageRuntime.cpp:2041:29: error: no member named 'mangleOpaqueTypeDescriptor' in 'swift::Mangle::ASTMangler'
02:05:19                     mangler.mangleOpaqueTypeDescriptor(opaque_type->getDecl()));
02:05:19                     ~~~~~~~ ^
02:05:19 /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/source/Target/SwiftLanguageRuntime.cpp:2069:24: error: no member named 'getUnderlyingTypeForOpaqueType' in 'swift::remoteAST::RemoteASTContext'
02:05:19             remote_ast.getUnderlyingTypeForOpaqueType(
02:05:19             ~~~~~~~~~~ ^
02:05:19 /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/source/Target/SwiftLanguageRuntime.cpp:2072:58: error: no member named 'getOrdinal' in 'swift::OpaqueTypeArchetypeType'
02:05:19                                             opaque_type->getOrdinal());
02:05:19                                             ~~~~~~~~~~~  ^
02:05:19 3 errors generated.
```

**Comment by dcci** [comment]
I do believe the issue here is that `lldb` auto merges from `5.1` to `stable` but maybe swift doesn't automerge from `5.1` to master, so the code diverged in unexpected ways. The fix is probably that of getting the compiler side of this patch on `master` for swift (as it doesn't seem to be there).

**Comment by jckarter** [comment]
I only intended for this to land in the 5.1 branch, sorry. The corresponding compiler change to master was hitting CI hiccups.

**Comment by jckarter** [comment]
I merged https://github.com/apple/swift/pull/24445 into swift master, so this should be fixed.

**Pull request merged**
