### PR TITLE
Account for the Swift renames of various Dictionary, Set, and String classes.

### PR DESCRIPTION
**Pull request by mikeash**
This is the lldb counterpart to this Swift PR: https://github.com/apple/swift/pull/21331

rdar://problem/46646438

### CODE REVIEW

**Review by dcci — APPROVED** [review]
LGTM

**Comment by mikeash** [comment]
https://github.com/apple/swift/pull/21331

@swift-ci please test

**Comment by mikeash** [comment]
https://github.com/apple/swift/pull/21331

@swift-ci please test

**Comment by mikeash** [comment]
apple/swift#21331

@swift-ci please test

**Comment by mikeash** [comment]
apple/swift#21331

@swift-ci please test

**Comment by mikeash** [comment]
apple/swift#21331

@swift-ci please test

**Pull request merged**
