### PR TITLE
Fix MSVC signed/unsigned conversion and size_t conversion warnings

### PR DESCRIPTION
**Pull request by hughbe**

### CODE REVIEW

**Comment by hughbe** [comment]
@swift-ci please test

**Review by jimingham — CHANGES_REQUESTED** [review]
The first of these two is in generic lldb code, and it is better to make this change in llvm.org and cherry-pick it to here or it might later cause merge conflicts when we sync up again.

**Comment by hughbe** [comment]
@swift-ci please test

**Comment by hughbe** [comment]
@swift-ci please test

**Comment by hughbe** [comment]
Thanks for taking a look. I've opened https://reviews.llvm.org/D30926

The upstream LLVM contribution process it pretty tricky so I might not have done it correctly - please let me know

**Pull request merged**
