### PR TITLE
Un-xfail a couple of tests that are now passing.

### PR DESCRIPTION
**Pull request by jimingham**
<rdar://problem/38484341>, <rdar://problem/38484268>

### CODE REVIEW

**Comment by jimingham** [comment]
@swift-ci please test

**Comment by vedantk** [comment]
The test failure is unrelated (it's resolved by https://github.com/apple/swift/pull/15409). I'll go ahead and merge this.

**Comment by jimingham** [comment]
Thanks!

**Comment by dcci** [comment]
@jimingham I'm afraid these are still failing on the CMake bot, see, e.g.

I'm going ahead and revert this commit to make the bot green(blue) again, and open a new radar for you to take a look.
I'm under the impression this might just be a mismerge or something not really cherry picked or a configuration error because these tests pass on the green dragon bot on llvm.org.

Some of the failures are related to 
```
15:37:58 error: no value found named 'DYLD_LIBRARY_PATH', aborting remove operation
```
https://ci.swift.org/job/oss-lldb-incremental-osx-cmake/224/console


```
15:39:02 FAIL: test_lldb_process_load_and_unload_commands_dsym (functionalities/load_unload/TestLoadUnload.py)
15:39:02 FAIL: test_lldb_process_load_and_unload_commands_dwarf (functionalities/load_unload/TestLoadUnload.py)
15:39:02 FAIL: test_lldb_process_load_and_unload_commands_gmodules (functionalities/load_unload/TestLoadUnload.py)
15:39:02 FAIL: test_set_working_dir (functionalities/process_launch/TestProcessLaunch.py)
```

**Pull request merged**
