### PR TITLE
Cleanup version printing

### PR DESCRIPTION
**Pull request by llvm-beanz**
This set of patches simplifies the LLDB version printing code and unifies it with LLVM.org. With this patch the new version output is:

> ./bin/lldb -version
lldb version 4.0.0 (git@github.com:apple/swift-lldb.git revision 8c6d50a8de05e1394cc0a99bfe18d015341d21f9) (lldb-360.0.0)
  Swift-3.0 (revision 455be3a65ebd6719f3f2e3b5376f02150dcc1e77)
  clang revision 758eef5c1fc08d4eb61488d1e5d5889dd48e0689
  llvm revision 2d42645e609dddb6d5188940a8fd69e799f81b52

This details the LLDB, LLVM, Clang and Swift revisions if available, and uses a unified output for all platforms.

### CODE REVIEW

**Comment by tfiala** [comment]
Hi @llvm-beanz,

Looks good.  I thought the code in packages/Python/lldbsuite/test/help/TestHelp.py would need to be updated to pass the version check, but it looks like that maybe was fixed already upstream.  Assuming that test continues to pass, this looks good to me.

Running the tests now:

@swift-ci Please test

**Comment by tfiala** [comment]
@swift-ci Please test

**Comment by tfiala** [comment]
@swift-ci Please test

**Comment by tfiala** [comment]
@swift-ci Please test OS X platform

**Comment by llvm-beanz** [comment]
I have one more llvm.org patch to land, and a corresponding cleanup on the swift side. I'll get it in this week.

**Comment by tfiala** [comment]
Rerunning the macOS tests.  That is a strange slice of failures.  We may have been hammering the box at that time as we were investigating fixes for the master-next branch directly on the box.

@swift-ci Please test OS X platform

**Comment by llvm-beanz** [comment]
@tfiala The failure is legitimate. It will be fixed in my next update to the PR.

**Comment by llvm-beanz** [comment]
@swift-ci Please test

**Comment by llvm-beanz** [comment]
@swift-ci Please test

**Comment by tfiala** [comment]
Right now both platforms are failing with compile errors.

**Comment by tfiala** [comment]
Okay I checked and it looks like mainline swift-lldb/master was temporarily broken by some change that is now fixed.  The compile errors above correspond to that breakage.

Here we go again:

@swift-ci Please test

**Comment by llvm-beanz** [comment]
The failure on this PR test was a bot cornfugraiton issue. The tests passed successfully, so I'm going to merge this PR.

**Comment by tfiala** [comment]
Yep, all good.  @shahmishal thanks for confirming.

**Pull request merged**
