### PR TITLE
Adjust for SVN r346157

### PR DESCRIPTION
**Pull request by compnerd**
Go plugin has been removed.  Update the code for that.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @dcci @adrian-prantl @JDevlieghere

**Comment by dcci** [comment]
sure.

**Comment by dcci** [comment]
Note that we have an auto merger that will pick up Jonas commit. So this is not really needed.

**Comment by JDevlieghere** [comment]
Thanks! I only resolved the merge conflicts, I should've double checked if there were references left.

**Pull request merged**
