### PR TITLE
Fix the Xcode project

### PR DESCRIPTION
**Pull request by JDevlieghere**
Add the SBReproducer to LLDB.framework.

### CODE REVIEW

**Comment by JDevlieghere** [comment]
rdar://48293780

**Comment by JDevlieghere** [comment]
@swift-ci please test and merge

**Comment by JDevlieghere** [comment]
@swift-ci please test and merge

**Comment by JDevlieghere** [comment]
@swift-ci please test and merge

**Comment by dcci** [comment]
@JDevlieghere linux is now likely to pass, but there's still a linker error on macOS, can you take a look?

```
16:49:16 Undefined symbols for architecture x86_64:
16:49:16   "lldb_private::repro::Registry::Replay(lldb_private::FileSpec const&)", referenced from:
16:49:16       lldb::SBReproducer::Replay() in SBReproducer.o
16:49:16 ld: symbol(s) not found for architecture x86_64
16:49:16 clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by JDevlieghere** [comment]
> Third Time's the Charm

@swift-ci please test and merge

**Comment by JDevlieghere** [comment]
Still failing, same error. There's only so many speculative commits I can do. This will have to wait until I'm unblocked to reproduce this locally.

**Comment by JDevlieghere** [comment]
#1330

**Pull request closed without merging**
