### PR TITLE
 "Temporarily" disable some lldb-mi tests that are unreliable.

### PR DESCRIPTION
**Pull request by adrian-prantl**
<rdar://problem/50050012>

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@eeckstein ^

**Comment by dcci** [comment]
I believe your commit upset `lit`

```
11:44:11 ValueError: couldn't parse text: '://50050012'
11:44:11 in expression: 'rdar://50050012'
11:44:11 in REQUIRES: directive on test line 1
11:44:11 
11:44:11 
```

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Pull request merged**
