### PR TITLE
[build-swift-cmake] Genericizes build script for use on Windows

### PR DESCRIPTION
**Pull request by AndrewSB**
This change depends on swift/utils/build-script also being updated to
run on Windows.

### CODE REVIEW

**Comment by dcci** [comment]
I think this is a good one _regardless_ of Windows support as it improves compatibility.
I'm going to spawn a bot run to make sure this doesn't break our bots.
Also, if you can try your changes on Linux and MacOS, that would be great.

**Comment by dcci** [comment]
@swift-ci please test

**Comment by AndrewSB** [comment]
🙃 I thought the same. 

This worked for me on linux and it looks like Jenkins is happy too. Should be good to merge

**Review by dcci — APPROVED** [review]
LGTM

**Comment by keith** [comment]
This appears to have broken the build, fix here: https://github.com/apple/swift-lldb/pull/341

**Pull request merged**
