### PR TITLE
`install-distribution` support for swift-lldb:stable

### PR DESCRIPTION
**Pull request by weliveindetail**
Follow-up from https://github.com/apple/swift-lldb/pull/1765 with another batch of changes

### CODE REVIEW

**Comment by weliveindetail** [comment]
test with apple/swift#26087
@swift-ci test

**Comment by weliveindetail** [comment]
test with apple/swift#26087
test with apple/swift-llvm#164
@swift-ci test

**Comment by weliveindetail** [comment]
This is still missing a patch to adjust the downstream-only part of swift-lldb. I will try and get this in today.

**Comment by weliveindetail** [comment]
test with apple/swift#26087
test with apple/swift-llvm#164
@swift-ci test

**Comment by weliveindetail** [comment]
build-script passes --lldb-use-sytem-debugserver
I will put this on hold until Monday

**Comment by weliveindetail** [comment]
This doesn't need the swift-llvm LLVMDistributionSupport.cmake change anymore, but I am still working on the debugserver issue. There are two potential solutions:
* quick-and-dirty: add dummy targets
* potentially better: always build&sign debugserver and with `--lldb-use-sytem-debugserver` use the system one for testing (only)

Currently figuring out whats the best way.

**Comment by weliveindetail** [comment]
Proposed fix upstream: https://reviews.llvm.org/D64806

**Comment by weliveindetail** [comment]
test with apple/swift#26087
@swift-ci please test

**Comment by weliveindetail** [comment]
Rebased, fixed conflicts, hopefully works now

**Comment by weliveindetail** [comment]
test with apple/swift#26087
@swift-ci please test

**Comment by weliveindetail** [comment]
Milestone: build succeeds, Tests: not yet

**Comment by weliveindetail** [comment]
Cannot reproduce these errors locally, instead I am seeing different ones. This will take a few more days, I am afraid.

**Comment by compnerd** [comment]
@weliveindetail - what do you think of actually splitting this up such that the changes that are backports from upstream is a separate PR that we get merged first?  That really shouldn't cause any problems and should help reduce the diff here and make it obvious what is being changed for the functionality rather than to support it.

**Comment by weliveindetail** [comment]
Agree, maybe I should sort out this PR into two separate ones. The current PR failures seem to originate from differences between my lldb/swift merge-bases and TOT clang/llvm.

**Comment by weliveindetail** [comment]
Part 1: Distribution builds for swift-lldb:stable https://github.com/apple/swift-lldb/pull/1822

**Pull request closed without merging**
