### PR TITLE
[SwiftASTContext] Return the correct value.

### PR DESCRIPTION
**Pull request by dcci**

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci test

**Comment by dcci** [comment]
@adrian-prantl you touched this code but left this behind. Any particular reason or just an oversight?

**Comment by adrian-prantl** [comment]
I may have fixed the reason for this problem last week in https://github.com/apple/swift-lldb/pull/1686. If this passes, can you cherry-pick it to swift-5.1-branch? I'd consider it part of that patch.

**Comment by dcci** [comment]
@adrian-prantl sure.

**Pull request merged**
