### PR TITLE
Weak link libswiftCore.dylib from repl_swift

### PR DESCRIPTION
**Pull request by scallanan**
This severs a build dependency on the swift standard library, simplifying the Mac OS X build.

### CODE REVIEW

**Comment by scallanan** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
:-( This will impact REPL launch times, which are already pretty bad. Are there any alternatives here?

**Comment by scallanan** [comment]
Would RTLD_LAZY be better?

**Comment by jrose-apple** [comment]
Sean talked to me in person and relayed that dlopen would not be significantly slower than static linking here.

**Pull request merged**
