### PR TITLE
Change for @_private imports

### PR DESCRIPTION
**Pull request by aschwaighofer**
Matching swift PR #20428

### CODE REVIEW

**Comment by aschwaighofer** [comment]
Please test with following PR:
https://github.com/apple/swift/pull/20428

@swift-ci Please test

**Review by dcci — APPROVED** [review]

**Comment by aschwaighofer** [comment]
Please test with following PR:
apple/swift#20428

@swift-ci Please test

**Comment by aschwaighofer** [comment]
Please test with following PR:
https://github.com/apple/swift/pull/20428

@swift-ci Please test

**Comment by aschwaighofer** [comment]
Please test with following PR:
https://github.com/apple/swift/pull/20428

@swift-ci Please test

**Pull request merged**
