### PR TITLE
Fix for TypePreservingNSNumber

### PR DESCRIPTION
**Pull request by egranata**

### CODE REVIEW

**Comment by jckarter** [comment]
A comment in the Swift implementation that LLDB relies on its layout would be helpful. Is there anything we could do to help isolate you from changes in the future? We don't want the implementation details of these classes to be ABI.

**Comment by egranata** [comment]
@jckarter I'd like to keep this pull request minimal since it's already a fair chunk of magic and it's for the 3.0 branch. I am happy to put all the comments you want on master though!

As for insulating us from the internals, we do need to know the type of the data and where to read it from. If you can expose that to us in a way you're comfortable with, then by all means. Maybe magic symbols we can look up and an agreed-upon encoding?

**Comment by jckarter** [comment]
Sure, this looks good for 3.0. Offset symbols seem like a reasonable way to expose the layout if you need it.

**Comment by scallanan** [comment]
I can honestly say that I have never been more pleased to approve a patch than today.
Looks Good To Me.

**Pull request merged**
