### PR TITLE
[stable] Add SwiftRuntimeReporting instrumentation plugin to receive runtime issues from the Swift language runtime

### PR DESCRIPTION
**Pull request by kubamracek**
This implements the LLDB part of the "Runtime Issues" features of
- Swift dynamic exclusivity violations
- Swift 3 @objc inference

See <https://github.com/apple/swift/pull/10293>, which implements the Swift counterpart of the interface/ABI. Basically, the Swift runtime provides a symbol and a structure that describes the issue details. LLDB then breaks on this symbol, extracts the info, and provides it via the extended info JSON and extended backtraces (GetStopReasonExtendedBacktraces). See the added testcases for example usage.

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
Let's test this, but the test will fail (the Swift change isn't merged into master yet).

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by vedantk** [comment]
This PR addresses all of my comments from an earlier round of review. LGTM.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Pull request merged**
