### PR TITLE
[Swift] Don't change access control for property wrappers.

### PR DESCRIPTION
**Pull request by dcci**
While here, add coverage for property wrappers (which we missed before).

<rdar://problem/51843757>

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci test

**Comment by dcci** [comment]
[I also cherry-picked some NFC changes to make sure this didn't conflict].

**Review by DougGregor — APPROVED** [review]
LGTM!

**Comment by dcci** [comment]
@swift-ci test and merge

**Pull request merged**
