### PR TITLE
Add a test for swift split debug-info

### PR DESCRIPTION
**Pull request by fjricci**
This is another re-upload of #289, against stable.

### CODE REVIEW

**Comment by fjricci** [comment]
@swift-ci please test

**Comment by dcci** [comment]
@fjricci really thank you for your patience! This LGTM.

**Review by dcci — APPROVED** [review]

**Comment by fjricci** [comment]
No problem - thanks for your help!

**Comment by fjricci** [comment]
@dcci - what's the procedure for porting this to upstream-with-swift after merging into stable? Another PR?

**Comment by dcci** [comment]
Yes. Just makes sure it compiles there. The linux failure doesn't seem related to your changes. I'll take a look and merge this PR for you.

**Comment by dcci** [comment]
@swift-ci test and merge

**Comment by dcci** [comment]
@swift-ci please test

**Comment by dcci** [comment]
@fjricci feel free to merge it if it passes and it's green. I might not have a lot of time to follow this.

**Comment by dcci** [comment]
Actually, I can merge this.

**Comment by dcci** [comment]
Thanks for your contribution and don't hesitate to submit other patches if you have any. Hopefully the process is better now.

**Comment by fjricci** [comment]
Sorry about that, I'm out of the office for the next week or so and didn't get the chance.

**Pull request merged**
