### PR TITLE
 Adapt LLDB to swift compiler changes in inout type handling.

### PR DESCRIPTION
**Pull request by adrian-prantl**
The swift compiler no longer mangled inout types and instead uses
DWARF expressions to express indirectness.

<rdar://problem/39125153>

### CODE REVIEW

**Comment by adrian-prantl** [comment]
https://github.com/apple/swift/pull/15694
@swift-ci test

**Comment by jimingham** [comment]
Should we also pull out the code that was detecting the inout or @lvalue and doing the extra dereference?  That should be dead code now, and will only do harm if we trip across it later on.

**Comment by adrian-prantl** [comment]
https://github.com/apple/swift/pull/15694
@swift-ci test

**Comment by adrian-prantl** [comment]
https://github.com/apple/swift/pull/15694
@swift-ci test

**Pull request merged**
