### PR TITLE
Support multiple runtime library import paths

### PR DESCRIPTION
**Pull request by beccadax**
Matches changes in apple/swift#23175.

### CODE REVIEW

**Review by dcci — APPROVED** [review]

**Comment by beccadax** [comment]
Please test with following pull request:
apple/swift#23175

@swift-ci please smoke test

**Comment by beccadax** [comment]
Please test with following pull request:
apple/swift#23175

@swift-ci please smoke test

**Comment by beccadax** [comment]
Please test with following pull request:
apple/swift#23175

@swift-ci please test

**Comment by slavapestov** [comment]
Please test with following pull request:
apple/swift#23175

@swift-ci please test

**Pull request merged**
