### PR TITLE
Simplify GetLibrarySearchPaths to return a result vector. (NFC)

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by jimingham** [comment]
It doesn't look like you actually return the paths vector you made.

**Comment by adrian-prantl** [comment]
Oddly enough, this dis not trigger a warning during compilation. Thanks for noticing!

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Pull request merged**
