### PR TITLE
Swift 4.0 branch swift merge

### PR DESCRIPTION
**Pull request by llvm-beanz**
Merge swift support from master into swift-4.0-branch.

### CODE REVIEW

**Comment by llvm-beanz** [comment]
@swift-ci please test

**Comment by llvm-beanz** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/7049

@swift-ci please test

**Comment by llvm-beanz** [comment]
@swift-ci please test

**Comment by llvm-beanz** [comment]
@swift-ci please test

**Comment by llvm-beanz** [comment]
Merging tis even without successful PR test because it is better than what we have at the moment, and I can't keep fighting with the PR testing system. The last attempt at PR testing was failing to build Swift.

**Comment by gottesmm** [comment]
@llvm-beanz This is the wrong approach. Where was it failing to build Swift? You should talk with the swift buildczar in such situations. If your change breaks swift PR testing, many people will be very unhappy...

**Comment by gottesmm** [comment]
@llvm-beanz I just talked with Chris, he told me that this does not affect mainline swift testing. Sorry for the noise!

**Pull request merged**
