### PR TITLE
Remove unnecessary use of ArchetypeType::isSelfDerived()

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@egranata Does this look reasonable?

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by egranata** [comment]
@slavapestov Assuming that true is the right answer for the question isSelfDerived() was asking before, then, yeah, sure.

Keep in mind that we are undergoing a huge reformatting of LLDB today, so you may want to hold off on committing this; @tfiala might have a more exact timeline for you

**Comment by tfiala** [comment]
I don't think there's an issue committing on swift-lldb/master.  We've done what I expect to be the final merge from swift-lldb/master => swift-lldb/master-next before the Great Code Formatting tsunami washes over us (likely tomorrow).

**Comment by tfiala** [comment]
The failure on the Linux build is a non-issue.  (Timeout accrued in no method, so rerun of timed out file isn't clearing the error properly.  There's a bug on that).

This should be fine to go in.

**Pull request merged**
