### PR TITLE
Cmake dependency fixups

### PR DESCRIPTION
**Pull request by llvm-beanz**
This patch merges in a bunch of changes from LLVM.org to accurately specify LLDB's library dependencies between itself, LLVM, and Clang. It also adds in accurate specification of LLDB's dependencies on Swift, and uses Swift's new CMake package support to import Swift's library dependency graph into the LLDB project.

### CODE REVIEW

**Comment by llvm-beanz** [comment]
@swift-ci please clean test

**Comment by llvm-beanz** [comment]
@swift-ci please clean test OS X platform

**Comment by llvm-beanz** [comment]
This PR failed PR testing because swift's swift-4.0-branch doesn't have my PR from earlier today. We can probably just sit on this for a while.

**Comment by gottesmm** [comment]
FYI Chris, if anything here is dependent on the cmake commits from the past day, some issues came up. I reverted in: apple/swift#7517.

**Comment by llvm-beanz** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
@llvm-beanz smoke test is not supported with lldb repo.

**Comment by llvm-beanz** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by llvm-beanz** [comment]
This PR is all CMake, which is only used on Linux LLDB builds because the OS X ones use Xcode. With that in mind and the fact that this PR is needed to unblock build failures on Linux swift/master bots that are breaking PR testing. I'm going to merge this without the OS X bot completing.

**Pull request merged**
