### PR TITLE
Fix the Hashed Container formatter for capacity->bucketCount

### PR DESCRIPTION
**Pull request by jimingham**
<rdar://problem/36847830>

### CODE REVIEW

**Comment by jimingham** [comment]
@swift-ci please test

**Review by dcci — CHANGES_REQUESTED** [review]
Please consider adding these tests to the `swiftpr` category.

**Comment by dcci** [comment]
@shahmishal this is failing on linux because the process gets killed (maybe OOM). Can you please take a look?

**Comment by jimingham** [comment]
@dcci This test definitely belongs in the swifter set, but I'm a little worried about doing this piecemeal.

**Comment by dcci** [comment]
@jimingham up to you, if you don't want to do that, I'll do it for you (but I don't see a problem with doing this incrementally, actually, I think it's the best way).

**Comment by jimingham** [comment]
That failure was the the linker timing out trying to build some part of the tools.  Let's try again...

**Comment by jimingham** [comment]
@swift-ci Please test

**Comment by jimingham** [comment]
@swift-ci please test

**Comment by dcci** [comment]
Looks like this started (it just needed a kick)

**Review by vedantk — CHANGES_REQUESTED** [review]
I'd like to see the `swiftpr` decoration added before this goes in (as soon as we deem a test as reliable).

**Comment by jimingham** [comment]
@swift-ci please test linux

**Comment by dcci** [comment]
@jimingham there are outstanding comments on this review, can you please take a look at them before rerunning the tests and merging? Thanks!

**Review by vedantk — APPROVED** [review]

**Comment by vedantk** [comment]
Thanks!

**Comment by vedantk** [comment]
@swift-ci test and merge

**Comment by vedantk** [comment]
@swift-ci test

**Comment by vedantk** [comment]
Hm, weird failure: https://ci.swift.org/view/Pull%20Request/job/swift-lldb-PR-Linux/90/console

**Comment by vedantk** [comment]
@swift-ci test and merge

**Comment by vedantk** [comment]
@swift-ci test

**Pull request merged**
