### PR TITLE
Support Linux on z as a Swift platform

### PR DESCRIPTION
**Pull request by bryanpkc**
We have ported Swift to Linux on IBM z Systems. Please cherry-pick these commits from upstream LLDB to enable LLDB/REPL to work on the SystemZ target.

There are a couple of conflicts in source/Core/Scalar.cpp, which are resolved by using the current working solution from upstream LLDB. The uses of Scalar::APIntWithTypeAndValue() and getRawData() in the original code were not correct for big-endian systems.

### CODE REVIEW

**Comment by tfiala** [comment]
@swift-ci Please test

**Comment by tfiala** [comment]
> There are a couple of conflicts in source/Core/Scalar.cpp, which are resolved by using the current working solution from upstream LLDB. 

Yes, I've seen those.  We are keeping the swift-lldb/master-next refreshed every few weeks with new merges from upstream LLDB.  Those happened to be handled up there.

I'll have a look at this change.  (I also kicked off a PR test on our CI).

**Comment by tfiala** [comment]
@bryanpkc, it looks like these tests are failing on Ubuntu x86_64 with this change:

ERROR: [EXCEPTIONAL EXIT 6 (SIGABRT)] test_with_dwarf (lang/swift/variables/generic_struct_debug_info/generic_array/TestSwiftGenericStructDebugInfoGenericArray.py)
ERROR: [EXCEPTIONAL EXIT 6 (SIGABRT)] test_with_dwarf (lang/swift/local_closure_types/TestSwiftLocalClosureTypes.py)
ERROR: [EXCEPTIONAL EXIT 6 (SIGABRT)] test_with_dwarf (lang/swift/generic_type_of_nested_archetype/TestSwiftGenericTypeOfNestedArchetype.py)

Still waiting on OS X.

**Comment by tfiala** [comment]
The OS X Xcode build project also needs a few modifications to bring in some new files:
```
Undefined symbols for architecture x86_64:
  "RegisterContextCorePOSIX_s390x::RegisterContextCorePOSIX_s390x(lldb_private::Thread&, lldb_private::RegisterInfoInterface*, lldb_private::DataExtractor const&, lldb_private::DataExtractor const&)", referenced from:
      ThreadElfCore::CreateRegisterContextForFrame(lldb_private::StackFrame*) in liblldb-core.a(ThreadElfCore.o)
  "ABISysV_s390x::Terminate()", referenced from:
      lldb_private::SystemInitializerFull::Terminate() in SystemInitializerFull.o
  "RegisterContextLinux_s390x::RegisterContextLinux_s390x(lldb_private::ArchSpec const&)", referenced from:
      ThreadElfCore::CreateRegisterContextForFrame(lldb_private::StackFrame*) in liblldb-core.a(ThreadElfCore.o)
  "ABISysV_s390x::Initialize()", referenced from:
      lldb_private::SystemInitializerFull::Initialize() in SystemInitializerFull.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED
```

I can handle that part (the OS X Xcode build fix-up) once the broken tests on Ubuntu are addressed.

**Comment by bryanpkc** [comment]
I have committed an LLDB change upstream to fix the assertion failures.

**Comment by tfiala** [comment]
@Swift-ci please test

**Comment by bryanpkc** [comment]
@tfiala The failures don't seem related to the most recent LLDB change that I made. I can't reproduce the Linux failure here.

**Comment by tfiala** [comment]
@bryanpkc, it looks like the swift that was synched did not yet pick up a fix earlier today for the broken linkage we saw there.

The first build that had the fix on our master-branch Ubuntu builders was:
https://ci.swift.org/job/oss-lldb-incremental-linux-ubuntu-14_04/3426/

We'll kick off another build.  Meanwhile, I'll get you a PR for your set that will fix that OS X side.  That's just going to be a minor project change.  Then we can see if anything else is broken on the OS X side behind that.

**Comment by tfiala** [comment]
@swift-ci Please test Linux platform

**Comment by tfiala** [comment]
The Linux build came back clean now.  I'll get you the OS X changes in the morning so we can clear that side and get this in.

**Comment by bryanpkc** [comment]
@tfiala Thanks!

**Comment by tfiala** [comment]
@bryanpkc, it looks like you just need to pull in this change as well:

```
commit 464d3f289ba259791c0d02ae926e0e62e7543b36
Author: Greg Clayton <gclayton@apple.com>
Date:   Thu Apr 14 13:05:21 2016

    Fix Xcode project after recent s390x changes.



    git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@266361 91177308-0d34-0410-b5e6-96231b3b80d8
```

Can you grab r266361 and add it to your PR?  I started getting it ready but realized it must have already been fixed upstream for the Xcode project.

**Comment by tfiala** [comment]
(If you end up having trouble merging the Xcode file, which isn't always the easiest thing to merge, let me know.  I'm in the process of merging LLVM.org lldb svn trunk into the swift-lldb/master-next branch, which at some point in the future will move to swift-lldb/master.  If you have trouble with the Xcode merge, we likely can do a simple cherry-pick from master-next once I'm done with that.  Might not be until early next week though, so if you can try to merge it, that might be faster).

**Comment by tfiala** [comment]
@bryanpkc - nm, I'll merge it for you and get it to you.  You won't have an easy way to check it and it is probably not going to be an easy merge since we're a little out of sync between LLVM.org and GitHub swift-lldb w/r/t that particular file.

Working on this now...

**Comment by tfiala** [comment]
@bryanpkc, I sent a PR your way to pull into your branch, that should get Xcode building here:

https://github.com/linux-on-ibm-z/swift-lldb/pull/1

Once you have that in here, we can get the CI testing OS X again.

**Comment by tfiala** [comment]
@swift-ci Please test OS X platform

**Comment by tfiala** [comment]
I'm going to pull this in  The OS X side had two tests failing, but those also have been failing on master after this change:
```
Pending QOI improvements, reinstate implicit bridging conversions.
```

**Comment by bryanpkc** [comment]
@tfiala Todd, thank you so much for the extra effort on your part to get this in!

**Comment by tfiala** [comment]
My pleasure :-)

**Pull request merged**
