### PR TITLE
 Add -fmodule-map-file= to RemapClangImporterOptions whitelist

### PR DESCRIPTION
**Pull request by adrian-prantl**
See discussion https://github.com/apple/swift-lldb/pull/1369

(cherry picked from commit 14b40731018c79df8b2e9c5fc30678aae0e320a2)

### CODE REVIEW

**Comment by DavidGoldman** [comment]
@adrian-prantl is it possible to merge this into a minor update of swift 5.0? Not sure how the release process for minor updates works.

**Comment by adrian-prantl** [comment]
I'm aware of this; at this time I can't make any promises, but I'll see what we can do.

**Comment by DavidGoldman** [comment]
Gotcha, thank you!

**Comment by tkremenek** [comment]
@swift-ci test and merge

**Pull request merged**
