### PR TITLE
[Swift] Remove old pre-RemoteAST code path for getting field offsets

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
I merged this to upstream-with-swift a while back but it never ended up in the stable branch. What branch do changes have to go in these days?

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by dcci** [comment]
@slavapestov yes, merging to stable is correct (sorry, we changed our model several times in the past 4 months so things may be a little confusing).

**Pull request merged**
