### PR TITLE
LLDB changes required for stable branch update

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
https://github.com/apple/swift/pull/15088
apple/swift-clang#168
apple/swift-compiler-rt#18
apple/swift-llvm#80

@swift-ci test

**Comment by fredriss** [comment]
@swift-ci please test linux platform

**Comment by fredriss** [comment]
apple/swift#15088
apple/swift-clang#168
apple/swift-compiler-rt#18
apple/swift-llvm#80

@swift-ci please clean test linux platform

**Comment by fredriss** [comment]
apple/swift#15088
apple/swift-clang#168
apple/swift-compiler-rt#18
apple/swift-llvm#80

@swift-ci please clean test

**Comment by fredriss** [comment]
apple/swift#15088
apple/swift-clang#168
apple/swift-compiler-rt#18
apple/swift-llvm#80

@swift-ci please test

**Comment by shahmishal** [comment]
apple/swift#15088
apple/swift-clang#168
apple/swift-compiler-rt#18
apple/swift-llvm#80

@swift-ci please test

**Comment by fredriss** [comment]
apple/swift#15088
apple/swift-clang#168
apple/swift-compiler-rt#18
apple/swift-llvm#80

@swift-ci please test

**Comment by fredriss** [comment]
apple/swift#15088
apple/swift-clang#168
apple/swift-compiler-rt#18
apple/swift-llvm#80

@swift-ci please test

**Pull request merged**
