### PR TITLE
Fix parsing of fix-its in SwiftRuntimeReporting

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
Test case?

**Comment by kubamracek** [comment]
I can add an LLDB test for the feature in <https://github.com/apple/swift/pull/10893> (once it lands), that will exercise the new codepaths.  Does that sound good?

Otherwise, do you have suggestions how to test this?

**Comment by kubamracek** [comment]
I've added a testcase that simulates the ABI of the debugger hook in libswiftCore.dylib.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Pull request merged**
